import {readFileSync} from 'node:fs';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {beforeAll,afterAll,it,expect} from 'vitest';
import app from '../src/index';
import {mintSession} from '../src/auth';
const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'roadmap-http',modules:true,script:"export default {fetch(){return new Response('ok')}}",d1Databases:{DB:'roadmap-http-db'}}]}));
let db:D1Database,env:any,tokens:Record<string,string>={};
beforeAll(async()=>{db=await mf.getD1Database('DB');for(const file of ['0001_init.sql','0010_roadmap.sql']){const sql=readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8').split('\n').filter(x=>!x.trimStart().startsWith('--')).join('\n');await db.batch(sql.split(';\n').map(x=>x.trim()).filter(Boolean).map(x=>db.prepare(x)));}
 env={DB:db,SESSION_SECRET:'synthetic-roadmap-test',ENVIRONMENT:'dev',PUBLIC_ORIGIN:'https://app.test',ROADMAP_PUBLISHER_IDS:'publisher,verifier',ROADMAP_VERIFIER_IDS:'verifier,publisher',ROADMAP_SUMMARY_REVIEWER_IDS:'verifier'};
 for(const id of ['publisher','verifier','ordinary']){await db.prepare('INSERT INTO principal(id,email_hash,provisioned,support,created_at) VALUES(?,?,1,0,?)').bind(id,id,'2026-09-18').run();tokens[id]=await mintSession(env,id,'user');}
},60000);afterAll(()=>mf.dispose());
const paths:Record<string,string>={publish:'events',summary:'summaries',verify:'verifications',redact:'redactions'};
async function call(action:string,params:any,actor?:string,mode?:string,confirm?:string,mcp=false,extra:any={}){
 const headers:any={'content-type':'application/json',...(actor?{authorization:'Bearer '+tokens[actor]}:{}),...extra};
 const args={capability:'cap.ops.roadmap_'+action,params,...(mode?{mode}:{}),...(confirm?{confirm_token:confirm}:{})};
 const body=mcp?{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:action==='read'?'read':'danger',arguments:args}}:{params,mode,confirm_token:confirm};
 const url=mcp?'https://app.test/mcp':action==='read'?'https://app.test/v2/roadmap':'https://app.test/v2/roadmap/'+paths[action];
 const r=await app.fetch(new Request(url,{method:!mcp&&action==='read'?'GET':'POST',headers,...(!mcp&&action==='read'?{}:{body:JSON.stringify(body)})}),env);const raw:any=await r.json();return mcp?(raw.result?.structuredContent??raw.result??raw):raw;
}
const event=(key=crypto.randomUUID())=>({idempotency_key:key,item_id:'roadmap-123',kind:'work_started',stage:'planned',state:'done',evidence:[{repo:'3d-review-app',kind:'issue',number:123}]});
async function commit(action:string,p:any,actor:string,mcp=false){const dry=await call(action,p,actor,'dry_run',undefined,mcp);expect(dry.ok).toBe(true);return call(action,p,actor,'execute',dry.result.confirm_token,mcp);}
it('anonymous, unpermitted authenticated and forged scope/actor writes fail',async()=>{const p={expected_cursor:0,event:event()};for(const actor of [undefined,'ordinary'])expect((await call('publish',p,actor,'dry_run')).ok).toBe(false);for(const key of ['actor','role','environment','scope','tenant_id'])expect((await call('publish',{...p,[key]:'forged'},'publisher','dry_run')).ok).toBe(false);});
it('HTTP publish uses existing auth and confirmation; public claim does not mark Done',async()=>{const p={expected_cursor:0,event:event()};expect((await call('publish',p,'publisher','execute')).ok).toBe(false);const result=await commit('publish',p,'publisher');expect(result.ok).toBe(true);expect(result.result.sequence).toBe(1);const read=await call('read',{});expect(read.result.cursor).toBe(1);expect(read.result.items[0].value.stages.planned.state).toBe('pending');expect(read.result.events[0].value.kind).toBe('claim');for(const secret of ['publisher','synthetic-roadmap-test','request_hash','idempotency_key'])expect(JSON.stringify(read.result)).not.toContain('"'+secret+'"');});
it('MCP shares the same store; issuer cannot self-verify',async()=>{const p={expected_cursor:1,event:event()};const result=await commit('publish',p,'publisher',true);expect(result.ok).toBe(true);const read=await call('read',{},undefined,undefined,undefined,true);expect(read.result.cursor).toBe(2);const v={expected_cursor:2,idempotency_key:crypto.randomUUID(),item_id:'roadmap-123',event_sequence:2,evidence:p.event.evidence,attestation:'independently_checked'};expect((await call('verify',v,'publisher','dry_run')).ok).toBe(false);const verified=await commit('verify',v,'verifier');expect(verified.ok).toBe(true);const final=await call('read',{});expect(final.result.items[0].value.stages.planned.state).toBe('done');expect(final.result.items[0].value.stages.planned.reason).toContain('attestation');});
it('cookie-auth writes require matching origin; expired authorization cannot publish',async()=>{const p={expected_cursor:3,event:event()};for(const origin of [undefined,'https://other.test']){const result=await call('publish',p,undefined,'dry_run',undefined,false,{cookie:'session='+tokens.publisher,...(origin?{origin}:{})});expect(result.ok).toBe(false);}expect((await call('publish',p,undefined,'dry_run',undefined,false,{cookie:'session='+tokens.publisher,origin:'https://app.test'})).ok).toBe(true);
 await db.prepare("UPDATE session SET expires_at='2000-01-01T00:00:00.000Z' WHERE principal_id='publisher'").run();expect((await call('publish',p,'publisher','dry_run')).ok).toBe(false);tokens.publisher=await mintSession(env,'publisher','user');});
it('reviewed summary rejects seeded contact data and default publisher lacks narrative authority',async()=>{const p={expected_cursor:3,idempotency_key:crypto.randomUUID(),item_id:'roadmap-123',summary:{title:'Live roadmap',feedback:'Progress visibility requested.',priority:'Ongoing work needs visible status.',scope:'Read-only public progress.',outcome:'Not measured.',recurrence:'Unknown.'},publication_review:[{repo:'3d-review-app',kind:'pull',number:123}]};expect((await call('summary',p,'publisher','dry_run')).ok).toBe(false);expect((await call('summary',{...p,summary:{...p.summary,feedback:'person@example.test'}},'verifier','dry_run')).ok).toBe(false);expect((await commit('summary',p,'verifier')).ok).toBe(true);});
it('redaction through MCP clears live public current/history and changes generation',async()=>{const p={expected_cursor:4,idempotency_key:crypto.randomUUID(),item_id:'roadmap-123'};expect((await commit('redact',p,'verifier',true)).ok).toBe(true);const read=await call('read',{});expect(read.result.generation).toBe(1);expect(read.result.items).toEqual([]);expect(read.result.events).toHaveLength(1);expect(JSON.stringify(read.result)).not.toContain('Live roadmap');});
it('SSE reconnect honors cursor/generation and sends reset without removed payload or actor data',async()=>{const response=await app.fetch(new Request('https://app.test/v2/roadmap/stream?after=0&generation=0',{headers:{'last-event-id':'2'}}),env);expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('no-store');const reader=response.body!.getReader(),first=await reader.read(),wire=new TextDecoder().decode(first.value);expect(wire).toContain('event: reset');expect(wire).toContain('"generation":1');expect(wire).not.toContain('Live roadmap');expect(wire).not.toContain('publisher');await reader.cancel();});
it('SSE malformed cursor rejected; public history shares redaction generation',async()=>{const response=await app.fetch(new Request('https://app.test/v2/roadmap/stream?after=NaN'),env);expect(response.status).toBe(400);const r=await app.fetch(new Request('https://app.test/v2/roadmap/items/roadmap-123/history'),env);const body:any=await r.json();expect(body.result.generation).toBe(1);expect(body.result.events).toHaveLength(1);expect(body.result.events[0].value.kind).toBe('redaction');});
