name = "3d-review"
main = "src/index.ts"
compatibility_date = "2026-09-01"
[vars]
ENVIRONMENT = "dev"
[[d1_databases]]
binding = "DB"
database_name = "3d-review"
database_id = "5d4cc260-a7b1-47cc-b03d-ed4f60d324c3"

[[rules]]
type = "Text"
globs = ["**/*.yaml"]
fallthrough = true
