import test from 'node:test';import assert from 'node:assert/strict';import {createLiveFeed} from './live.js';
class Source {static last;constructor(url){this.url=url;this.handlers={};Source.last=this;}addEventListener(n,f){this.handlers[n]=f;}close(){this.closed=true;}send(n,data){this.handlers[n]?.({data:JSON.stringify(data)});}}
const result=(cursor=1,generation=0,items=[{value:{id:'roadmap-123'}}])=>({ok:true,result:{cursor,generation,items,item_next:null,last_event_at:'2026-09-18T19:00:00.000Z',source_mode:'dev_provisional'}});
const tick=()=>new Promise(r=>setImmediate(r));
test('live change rereads same authority without credentials or page reload',async()=>{let current=result(),latest,requests=[];const feed=createLiveFeed({EventSourceClass:Source,fetcher:async(...args)=>{requests.push(args);return {ok:true,json:async()=>current}},onChange:s=>latest=s});feed.start();await tick();assert.equal(latest.snapshot.cursor,1);assert.equal(requests[0][1].credentials,'omit');current=result(2);Source.last.send('change',{cursor:2,generation:0});await tick();assert.equal(latest.snapshot.cursor,2);feed.dispose();});
test('redaction generation immediately clears cached view and old in-flight read cannot restore it',async()=>{let latest,resolveRead,count=0;const feed=createLiveFeed({EventSourceClass:Source,fetcher:async()=>{count++;if(count===2)await new Promise(r=>resolveRead=r);return {ok:true,json:async()=>count>=3?result(3,1,[]):result()}},onChange:s=>latest=s});feed.start();await tick();feed.refresh();await tick();Source.last.send('reset',{cursor:3,generation:1});assert.equal(latest.snapshot,null);resolveRead();await tick();await tick();assert.deepEqual(latest.snapshot.items,[]);assert.equal(latest.snapshot.generation,1);feed.dispose();});
test('disconnect is labeled and fallback timer is bounded; pause closes stream',async()=>{let latest,scheduled=[];const feed=createLiveFeed({EventSourceClass:Source,fetcher:async()=>({ok:true,json:async()=>result()}),setTimer:(fn,ms)=>{scheduled.push(ms);return 1},clearTimer:()=>{},onChange:s=>latest=s});feed.start();await tick();Source.last.onerror();assert.match(latest.connection,/disconnected/);assert.deepEqual(scheduled,[15000]);feed.pause();assert.equal(Source.last.closed,true);feed.dispose();});
test('initial failure does not invent progress and disposed response is ignored',async()=>{let latest,release;const feed=createLiveFeed({EventSourceClass:Source,fetcher:()=>new Promise(r=>release=r),onChange:s=>latest=s});feed.start();feed.dispose();release({ok:true,json:async()=>result()});await tick();assert.equal(latest.snapshot,null);});
test('redaction replaces the reconnect URL and stale closed-stream events cannot clear the accepted snapshot',async()=>{let current=result(),latest,states=[];const feed=createLiveFeed({EventSourceClass:Source,fetcher:async()=>({ok:true,json:async()=>current}),onChange:s=>{latest=s;states.push(s);}});feed.start();await tick();feed.pause();feed.resume();await tick();const old=Source.last;assert.match(old.url,/generation=0/);current=result(3,1,[{value:{id:'roadmap-456'}}]);old.send('reset',{cursor:3,generation:1});assert.equal(latest.snapshot,null);await tick();await tick();assert.deepEqual(latest.snapshot.items,[{id:'roadmap-456'}]);const accepted=latest.snapshot;assert.equal(old.closed,true);assert.notEqual(Source.last,old);assert.match(Source.last.url,/after=3&generation=1/);const before=states.length;old.send('reset',{cursor:1,generation:0});assert.equal(states.length,before);assert.equal(latest.snapshot,accepted);Source.last.onerror();Source.last.onopen();Source.last.send('heartbeat',{cursor:3,generation:1});await tick();assert.equal(latest.snapshot,accepted);assert.equal(states.slice(before).some(s=>s.snapshot===null),false);feed.dispose();});
