import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {windowItems,STAGES} from './model.js';import {renderTable} from './page.js';
const row=(n,done)=>({id:'roadmap-'+n,title:'Item '+n,version:null,updated_at:'2026-09-18T00:00:00.000Z',remaining:'Pending',links:[],provenance:{feedback:'Unknown'},history:[],stages:Object.fromEntries(STAGES.map(k=>[k,{state:done?'done':'pending',reason:'Evidence not supplied',evidence:[]}]))});
test('rolling history retains complete counts and disclosure exposes all rows',()=>{const items=Array.from({length:35},(_,n)=>row(n,n>=23));const w=windowItems(items);assert.deepEqual([w.active.length,w.activeTotal,w.completed.length,w.completedTotal],[20,23,10,12]);assert.equal(windowItems(items,true).active.length,23);assert.equal(items.length,35);});
test('table escapes prose, labels exact stages and empty state',()=>{const item=row(1,false);item.title='<img src=x onerror=alert(1)>';const d=new JSDOM(renderTable([item],'Active work')).window.document;assert.equal(d.querySelector('img'),null);assert.equal(d.querySelectorAll('thead th').length,9);assert.match(d.body.textContent,/<img/);assert.match(d.body.textContent,/Not verified/);assert.match(renderTable([],'Completed items'),/No completed items/);});

test('roadmap shell mounts the shared version and text-only changelog behavior',async()=>{
 const {readFile}=await import('node:fs/promises');const {initVersionBadge}=await import('../changelog.js');const dom=new JSDOM(await readFile(new URL('./index.html',import.meta.url),'utf8'));const doc=dom.window.document;doc.getElementById('changelog').showModal=function(){this.open=true;};doc.getElementById('changelog').close=function(){this.open=false;};
 const calls=[];const badge=initVersionBadge({doc,fetchImpl:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>url==='/v2/health'?{result:{version:'0.12.0',build:'0.12.0+abc1234',commit:'abc1234',release_source:'def1234'}}:{current:'0.12.0',versions:[{version:'0.12.0',status:'candidate',sections:{added:['<img src=x>']}}]}};}});await badge.ready;assert.equal(doc.getElementById('version').textContent,'Version 0.12.0');doc.getElementById('version').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(doc.querySelector('#changelog-body img'),null);assert.match(doc.getElementById('changelog-body').textContent,/<img src=x>/);assert.equal(calls.filter(c=>c.url==='/v2/health').length,1);assert.ok(calls.every(c=>c.options.credentials==='omit'));assert.ok(doc.querySelector('script[src="/changelog.js"]'));
});

test('reported delivery is visible without becoming verified completion',()=>{const item=row(140,false);item.reported={production:{state:'done',version:'0.12.1',sequence:2},dev:{state:'done',version:'0.12.1',sequence:1}};item.provenance.scope='Make delivery understandable.';const d=new JSDOM(renderTable([item],'Active work')).window.document;assert.match(d.body.textContent,/Reported: done · 0.12.1/);assert.match(d.body.textContent,/Not verified/);assert.match(d.body.textContent,/Review reported DEV, Production evidence/);assert.match(d.body.textContent,/Make delivery understandable/);assert.equal(windowItems([item]).completedTotal,1);assert.equal(item.stages.production.state,'pending');});
test('blockers and accepted evidence are distinct from unverified reports',()=>{const item=row(140,false);item.reported={dev:{state:'blocked',blocker:'checks_failed'}};item.stages.built={state:'done',reason:'Independent acceptance',evidence:[{label:'Review',url:'https://github.com/klappy/3d-review-app/issues/140'}]};const d=new JSDOM(renderTable([item],'Active work')).window.document;assert.match(d.body.textContent,/Verified: ✅ Done/);assert.match(d.body.textContent,/Resolve reported DEV blocker: checks failed/);assert.match(d.body.textContent,/Independent acceptance/);});
test('reviewed operational action, blocker and queue are available without opening disclosures',()=>{const item=row(140,false);item.operations={happening_now:'Production retry underway',blocker:'Build failed',next_action:'Retry corrected build',queue_order:'After feedback correction',reviewed_at:'2026-09-18T20:00:00Z'};const d=new JSDOM(renderTable([item],'Active work')).window.document;for(const text of ['Production retry underway','Build failed','Retry corrected build','After feedback correction']){const cell=[...d.querySelectorAll('td')].find(x=>x.textContent.includes(text));assert.ok(cell);assert.equal(cell.closest('details'),null);} });
