import {STAGES,LABELS,STATES,windowItems} from './model.js';
import {stagePresentation,nextAction,happeningNow,currentBlocker} from './model.js';
import {createLiveFeed} from './live.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=v=>new Date(v).toLocaleString(undefined,{timeZone:'UTC'})+' UTC';
const links=xs=>xs.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.label)}</a>`).join(' · ');
export function renderCards(items,label){
 if(!items.length)return `<p class="muted">No ${label.toLowerCase()} currently published.</p>`;
 return items.map(item=>`<article class="work-card"><h3>${esc(item.title)}</h3><p class="badges">${item.operations?.work_type?`<span>${esc(item.operations.work_type)}</span>`:''}${item.operations?.release_reference?`<span>Assigned ${esc(item.operations.release_reference)}</span>`:''}${item.operations?.release_impact?`<span>Reviewed ${esc(item.operations.release_impact)}</span>`:''}${item.operations?.breaking===true?'<span>Breaking change</span>':''}</p><p>${esc(item.provenance.scope??'Scope not yet reviewed.')}</p><p class="small">${item.version?'Release reference '+esc(item.version):'Release reference not recorded'} · ${links(item.links)}</p>
 <div class="stage-matrix" aria-label="Delivery stages">${STAGES.map(k=>{const p=stagePresentation(item,k);return `<div><strong>${LABELS[k]}</strong><span>${esc(p.report)}</span><small>${esc(p.label)}</small></div>`;}).join('')}</div>
 <dl class="actions"><dt>Now</dt><dd>${esc(happeningNow(item))}</dd><dt>Blocker</dt><dd>${esc(currentBlocker(item))}</dd><dt>Next</dt><dd>${esc(nextAction(item))}</dd><dt>Queue</dt><dd>${esc(item.operations?.queue_order??(item.operations?.queue_rank?'Position '+item.operations.queue_rank:'Not ranked'))}</dd></dl>
 ${item.operations?.reviewed_at?`<p class="small muted">Context reviewed ${esc(stamp(item.operations.reviewed_at))}</p>`:''}
 <details class="history" data-detail="${esc(item.id)}-history"><summary>Why this work · evidence · history</summary><dl>${Object.entries(item.provenance).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${STAGES.map(k=>`<p><strong>${LABELS[k]} evidence</strong>: ${esc(item.stages[k].reason)} ${links(item.stages[k].evidence)}</p>`).join('')}<ol>${item.history.map(e=>`<li><strong>${esc(e.kind)} · ${esc(stamp(e.at))}</strong><p>${esc(e.summary)}</p><p>${links(e.links)}</p></li>`).join('')}</ol><p class="small">Recent ${item.history.length} of ${item.history_count??item.history.length} events</p><button type="button" data-history="${esc(item.id)}">Read full history</button><div data-history-output="${esc(item.id)}"></div></details></article>`).join('');
}
export function mountRoadmap(doc=globalThis.document,createFeed=createLiveFeed){
 const output=doc.querySelector('#roadmap'),status=doc.querySelector('#roadmap-status'),refresh=doc.querySelector('#refresh'),all=doc.querySelector('#show-all');let latest=null,selected="now";
 const render=()=>{if(!latest)return;status.textContent=latest.error||'';
  if(!latest.snapshot){output.innerHTML='';return;}
  const opened=new Set([...output.querySelectorAll('details[open]')].map(x=>x.dataset.detail));
  const focused=doc.activeElement?.closest('details')?.dataset.detail;
  const s=latest.snapshot,w=windowItems(s.items,all.checked);
  const labels={past:'Past',now:'Now',next:'Next'},descriptions={past:'Completed work',now:'In progress',next:'Queued work'};
  output.innerHTML=`<p class="small freshness">${s.source_mode==='production_canonical'?'Production feed':'DEV provisional feed'} · Last recorded event ${latest.lastEventAt?esc(stamp(latest.lastEventAt)):'none yet'}</p><nav class="window-nav" aria-label="Work window">${['past','now','next'].map(k=>`<button type="button" data-window="${k}" aria-pressed="${selected===k}"><strong>${k==='past'?'← ':''}${labels[k]}${k==='next'?' →':''} · ${w[k+'Total']}</strong><span>${descriptions[k]}</span></button>`).join('')}</nav><div class="roadmap-lanes" data-selected="${selected}">${['past','now','next'].map(k=>`<section data-lane="${k}" class="${selected===k?'focus':''}"><h2>${labels[k]} <span>${w[k].length} of ${w[k+'Total']}</span></h2>${renderCards(w[k],descriptions[k])}</section>`).join('')}</div><section class="unclassified"><h2>Placement not published · ${w.unclassifiedTotal}</h2><p class="small muted">These items are not counted as active or queued until their workflow position is explicitly reviewed.</p>${renderCards(w.unclassified,'Unclassified work')}</section><details data-detail="transport" class="transport"><summary>Connection details · ${esc(latest.connection)}</summary><p>Last successful read ${esc(stamp(latest.fetchedAt))}. Event sequence ${s.cursor}.</p><p>Committed-event updates about every 2 seconds; disconnected polling every 15 seconds. Connection is not proof of completion.</p></details>`;
  for(const d of output.querySelectorAll('details')){if(opened.has(d.dataset.detail))d.open=true;if(focused===d.dataset.detail)d.querySelector('summary')?.focus();}
 };
 const historyClick=async(e)=>{const windowButton=e.target.closest('[data-window]');if(windowButton){selected=windowButton.dataset.window;render();output.querySelector(`[data-window="${selected}"]`)?.focus();return;}const button=e.target.closest('[data-history]');if(!button)return;const id=button.dataset.history,target=output.querySelector(`[data-history-output="${id}"]`);if(!target)return;button.disabled=true;const captured=latest?.snapshot?.generation;let after=Number(button.dataset.after??0);
  try{const response=await fetch(`/v2/roadmap/items/${encodeURIComponent(id)}/history?after=${after}&limit=25`,{credentials:'omit',cache:'no-store'});const body=await response.json();if(!response.ok||!body.ok)throw Error();const r=body.result;if(captured!==latest?.snapshot?.generation||r.generation!==captured){feed.refresh();return;}
   const rows=r.events.map(x=>`<li><strong>${esc(stamp(x.recorded_at))}</strong><p>${esc(x.value.kind==='claim'?'Publisher claim: '+x.value.claim.kind.replaceAll('_',' '):x.value.kind.replaceAll('_',' '))}</p>${x.value.summary?`<dl>${Object.entries(x.value.summary).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`:''}</li>`).join('');target.insertAdjacentHTML('beforeend',`<ol>${rows}</ol>`);if(r.next!==null){button.dataset.after=r.next;button.textContent='Read next history page';}else{button.textContent='History loaded';button.hidden=true;}
  }catch{target.textContent='History could not be loaded. Try again.';}finally{button.disabled=false;}
 };
 output.addEventListener('click',historyClick);
 const feed=createFeed({onChange:s=>{latest=s;render();}}),onRefresh=()=>feed.refresh();refresh.addEventListener('click',onRefresh);all.addEventListener('change',render);
 const visibility=()=>{if(doc.hidden)feed.pause();else feed.resume();};doc.addEventListener('visibilitychange',visibility);feed.start();
 return()=>{doc.removeEventListener('visibilitychange',visibility);refresh.removeEventListener('click',onRefresh);all.removeEventListener('change',render);output.removeEventListener('click',historyClick);feed.dispose();};
}
if(typeof document!=='undefined' && document.querySelector('#roadmap')){let dispose=mountRoadmap();globalThis.addEventListener('pagehide',()=>dispose());globalThis.addEventListener('pageshow',e=>{if(e.persisted)dispose=mountRoadmap();});}
