// Generated by scripts/roadmap-versions.mjs (lane 13). Do not edit by hand.
export const VERSIONS = {
 "current": "0.21.0",
 "shipped": [
  {
   "version": "0.21.0",
   "added": [
    "cards show child counts: assessment → responses; project → assessments · responses; workspace → projects · assessments · responses (component: Card) (#255)",
    "reports: build from real participant responses on DEV (attested synthetic path unchanged; held outside dev) (#256)"
   ],
   "changed": [],
   "fixed": []
  },
  {
   "version": "0.20.0",
   "added": [],
   "changed": [
    "component: Card — one v3 import point (ui/v3/components/card.js) for home/workspace/project/assessment cards, re-exporting the shared card (no copy) (#249)",
    "DEV mail: sends to any address when no allowlist is configured (team testing); an allowlist, when set, is still enforced (#252)",
    "Stepper: pending steps carry class \"todo\" instead of an empty class attribute (component: Stepper) (#251)",
    "setup wizard: \"step n of N\" count derives from the step list, not a hard-coded 4 (#253)"
   ],
   "fixed": []
  },
  {
   "version": "0.19.0",
   "added": [
    "public About page (#about) (#228)",
    "left sidebar on assessment and scope pages is the shared Sidebar tree (workspace → project → assessment), in step with the breadcrumbs (component: Sidebar tree) (#243)",
    "component: Sidebar tree — 0.16 left navigation Workspaces → Project → Assessment, current row from the same scope as Breadcrumbs (ui/v3/components/sidebar-tree.js; mounting via NEED 9→1) (#241)"
   ],
   "changed": [
    "component: Breadcrumbs — assessment context panel crumb row is the shared Breadcrumbs (Home › Workspace › Project › Assessment); v3 components served locally (#232)",
    "navigation: kit shell header crumb row is the shared Breadcrumbs component (Home › Workspace › Project › Assessment › Page), same as the assessment page (P0 12:32) (#239)",
    "demo header Exit demo / Sign in is one shared component (component: Header with Exit demo / Sign in) (#246)",
    "setup wizard: group rows use the glass look (--glass, --glass-edge, blur) instead of flat white cards (ruling 12:22) (#234)",
    "setup wizard: group rows use the design-system glass blur token (--blur-panel) instead of a hard-coded 8px (ruling 12:22) (#238)",
    "Stepper dots blur on the --blur-panel glass token (component: Stepper) (#244)",
    "component: Stepper — assessment page stage tab bar (Prepare · Collect · Understand · Improve) replaced by the wizard's shared Stepper; server stage = active dot, earlier stages ticked, each step links to its view; Permissions stays a separate link (captain ruling 12:28) (#230)",
    "results: band card and colour legend are one shared component (ui/v3/components/band-card.js) (#233)",
    "results and collect count line comes from one shared Response count component (#240)",
    "results \"Show evidence and details\" table comes from one shared Evidence table component (component: Evidence table) (#245)",
    "results review gate (state badge + Record my review / Choose a next step) comes from one shared Review gate component (component: Review gate) (#247)"
   ],
   "fixed": [
    "public links never land on sign-in (Read about it → #about, unknown hashes → home) (#228)",
    "look: flat white/teal restyle (#200) removed; design-system-v3 glass tokens govern header, cards and buttons again (ruling 12:22) (#235)",
    "setup review: participant note says plainly it is not sent or saved yet (review line + placeholder), replacing developer copy (#231)",
    "setup wizard: alert note uses the design-system --warning-ink token instead of a hard-coded red, so it stays readable in dark mode (#242)",
    "Stepper: completed steps are announced as \"completed\" to screen readers (component: Stepper) (#248)",
    "band card component is served by the local server and its tests stay off DEV assets (#236)"
   ]
  },
  {
   "version": "0.18.0",
   "added": [
    "component: Stepper — one progress stepper in ui/v3/components/stepper.js (glass dots, done ticks, optional hash links per step); the setup wizard composes it and lane 3 imports it for the assessment page (rulings 12:28, 12:34) (#227)",
    "results: provisional bands (≥75 Strong · 60–74 Growing · 40–59 Needs support · <40 Needs urgent attention; min 3 responses else More input needed) from the latest report's per-perspective and sub-dimension scores, labelled provisional; numbers behind \"Show evidence and details\" (component: Band card + legend) (#225)",
    "component: Breadcrumbs — one crumb row in fixed order Home › Workspace › Project › Assessment › Page (ui/v3/components/breadcrumbs.js; mounting via NEED 9→1) (#224)"
   ],
   "changed": [],
   "fixed": [
    "demo: exit to home and sign in from every demo screen (#222)",
    "permissions: people shown by name and email, not id (component: Member list, used on workspace, project and assessment permissions) (#226)"
   ]
  },
  {
   "version": "0.17.0",
   "added": [
    "v3 shell and tokens: no context tree, breadcrumbs, one primary action per page, plain state words; global restyle to the v3 prototype; sign-in per prototype frame 1.",
    "Home dashboard as the prototype card grid (Start a new 3D Review, continue cards).",
    "Four-step setup wizard following prototype frames 3–6, with safe resume after a dropped connection.",
    "Assessment page with state-driven primary; Record my review → Choose a next step; Next step page saves notes.",
    "Results as bands with legend, per-perspective counts, evidence toggle and table.",
    "Collect: settled + not-yet-confirmed counts, open/closed rows, one-line totals.",
    "Participant welcome and pager per prototype frames 8/9; phone-width fixes.",
    "Project form: lead organisation, language name + ISO code, cycle date; access codes and workspaces reachable from project settings."
   ],
   "changed": [],
   "fixed": []
  },
  {
   "version": "0.16.0",
   "added": [
    "Kit shell activated on the real signed-in root and scope-reading routes: Workspaces→workspace→project→assessment navigation, search and expansion, language state and account/version controls through a read adapter over the existing controllers."
   ],
   "changed": [
    "Persona evidence: 15/15 root integration tests and 71/71 adapter/scope/identity-reset/shell unit tests passed at the exact accepted source; 25/25 synthetic menu hit and click checks across five viewport cases in an independent isolated browser. At the corrected source, 100 affected/anchor tests passed independently with 10 meaningful failures on the uncorrected parent, and 26 real headless Chrome journeys (16 title/route/host/viewport, 4 Retry, 4 delayed completion, 2 demo disclosure) passed at 390×900 and 1440×900. Real provider account journey untested; satisfaction, confusion and frustration NOT MEASURED."
   ],
   "fixed": [
    "Account menu stacks above the shell context on phone widths so Sign out and Use another account receive pointer input; header keeps its standard heights and no horizontal overflow at 195px.",
    "Workspace, workspaces, projects and project pages keep their own visible heading when the kit shell is not hosting the page (non-kit entry such as /assess/); the kit host owns the title only when it is actually mounted.",
    "The demonstration-data disclosure stays visible through kit repaints, navigation, search and expansion instead of disappearing on first render.",
    "Every Retry control on a failed page is bound with one shared pending guard, so the second control (languages) works when assessments and languages both fail; stale retry results after navigation change nothing."
   ]
  }
 ],
 "forecast": {
  "version": "0.21.1",
  "bump": "patch",
  "units": [
   {
    "file": "13-1723.md",
    "bump": "patch",
    "lane": 13,
    "section": "Changed",
    "text": "roadmap: Versions section on /roadmap/ lists shipped releases and forecasts the next version from the waiting change files"
   },
   {
    "file": "1-1512.md",
    "bump": "patch",
    "lane": 1,
    "section": "Fixed",
    "text": "cards: child counts only include assessments and projects you can list (Bugbot carry 15:12)"
   }
  ]
 }
};
