// Generated by scripts/roadmap-versions.mjs (lane 13). Do not edit by hand.
export const VERSIONS = {
 "current": "0.26.5",
 "shipped": [
  {
   "version": "0.26.5",
   "added": [],
   "changed": [],
   "fixed": [
    "On the printed survey, a long passage name or link now wraps inside the passage box instead of running off the page. (#430)",
    "While you accept many invitations at once, the page now shows how many are done and a spinner, so you can see it is still working. (#431)"
   ]
  },
  {
   "version": "0.26.4",
   "added": [],
   "changed": [],
   "fixed": [
    "\"See invitations\" on Home now opens your list of invitations, not an emailed invitation you opened earlier and did not accept; emailed invitation links work as before. (#425)",
    "If you turn off \"Ask participants about themselves\" in setup after it was turned on in Prepare, the review now launches with it off. (#429)"
   ]
  },
  {
   "version": "0.26.3",
   "added": [],
   "changed": [],
   "fixed": [
    "A survey link opened with an unexpected setting now says which settings it accepts (token, resume_token) instead of only \"unknown link parameter\". (#419)",
    "Asking for the survey form with extra settings (such as a language) now says the language is chosen through translation, not on the form. (#419)",
    "The receipt returned by `GET /v2/participate/receipt` (cap.response.receipt) now names the review it belongs to; the on-screen receipt is unchanged. (#419)",
    "If the page reloads while you are setting up an assessment, the wizard now returns to the step you were on with your choices kept. (#422)",
    "The Project field in the assessment setup is now marked as required in the form itself, so the browser points to it if it is left empty, as it already does for Name and Active until. (#422)",
    "Translation requests that are far too large are now refused before being read, so an oversized request cannot slow the service. (#423)",
    "When you sign in and someone has invited you to a review, Home now says so and takes you to the invitation. (#424)"
   ]
  },
  {
   "version": "0.26.2",
   "added": [],
   "changed": [],
   "fixed": [
    "The assessment setup now marks every field you must fill in with \"(required)\": Name, Project, New project name and Language, as \"Active until\" already was; the language code stays optional. (#418)",
    "When you print a survey in another language, the \"Translating the form…\" message stays on screen until the form is ready, even if the page refreshes while it loads. (#418)"
   ]
  },
  {
   "version": "0.26.1",
   "added": [],
   "changed": [],
   "fixed": [
    "When the translation service answers slowly, the survey no longer waits forever for the rest of its reply; the same time limit now covers the whole answer. (#415)",
    "If saving a passage file fails partway, the uploaded file is cleaned up instead of being left behind in storage. (#415)",
    "Taking a survey's link twice at the same moment no longer creates two live links; both requests get the same link. (#415)",
    "The assessment setup now shows that \"Active until\" is required, next to \"Starts (optional)\". (#414)",
    "When a passage link is refused (for example one starting with http:// instead of https://), the link, title and passage you typed stay in the form so you can correct them instead of typing them again. (#414)",
    "On the participant survey, the \"answer required\" mark on a question clears as soon as you start typing an answer, not only when you leave the field. (#414)",
    "Printing a survey in another language now follows the language picker on screen even if the page refreshed while the form was loading, and the picker and Print survey button unlock correctly afterwards. (#414)",
    "Clicking Print survey twice quickly no longer prints the form twice; the button stays locked until the form is ready. (#414)"
   ]
  },
  {
   "version": "0.26.0",
   "added": [],
   "changed": [
    "The printed survey now says which project, assessment (with the language being evaluated, and the language it is printed in) and survey it belongs to, with the ids in small print, and carries the survey's one shared link as a QR code with the link under it and \"Helper: scan to enter this paper's answers\". A survey with no shared link yet says so on the paper instead of inventing one. Codes are still never printed. (#411)"
   ],
   "fixed": [
    "The printed survey now gives people room to write. Every \"Other (please describe)\" choice keeps its circle or box and has three full-width ruled lines right under it instead of a short blank after the words, and questions answered in words have five ruled lines instead of two. (#409)"
   ]
  }
 ],
 "forecast": {
  "version": null,
  "bump": null,
  "units": []
 }
};
