import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../../worker/index.js';
function db(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../../migrations/0001_vertical.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../../migrations/0002_guards.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../../migrations/0003_languages.sql',import.meta.url),'utf8'));const wrap=(sql,args=[])=>({bind(...a){return wrap(sql,a)},async first(){return sqlite.prepare(sql).get(...args)},async all(){return{results:sqlite.prepare(sql).all(...args)}},async run(){return sqlite.prepare(sql).run(...args)}});return{prepare:sql=>wrap(sql),async batch(ss){sqlite.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}};}
test('durable synthetic vertical flow; scope, confirmation, retry and HTTP/MCP semantics',async()=>{const env={DB:db(),APP_ENV:'local'};let cookie='',bearer='';async function call(path,method='GET',body,extra={}){const headers={'Content-Type':'application/json',Origin:'http://localhost:8787',...extra};if(cookie)headers.Cookie=cookie;if(bearer)headers.Authorization='Bearer '+bearer;const r=await worker.fetch(new Request('http://localhost:8787'+path,{method,headers,...(body?{body:JSON.stringify(body)}:{})}),env);const v=await r.json();return{r,v};}
 let x=await call('/v2/projects');assert.equal(x.r.status,401);x=await call('/v2/dev/session','POST',{});assert.equal(x.v.ok,true);cookie=x.r.headers.get('set-cookie').split(';')[0];x=await call('/v2/projects','POST',{name:'Synthetic'});const pid=x.v.result.id;assert.ok(pid);x=await call(`/v2/projects/${pid}/assessments`,'POST',{name:'Cycle 1',language:{new:{label:'Test'}}});const aid=x.v.result.id;assert.ok(aid);x=await call(`/v2/assessments/${aid}/surveys`,'POST',{template_id:'synthetic-demo',template_version:1});const sid=x.v.result.id;assert.ok(sid);x=await call(`/v2/assessments/${aid}/stage`,'POST',{stage:'collect'});assert.equal(x.v.ok,true);x=await call(`/v2/assessments/${aid}/surveys/${sid}/codes`,'POST',{count:1});assert.equal(x.v.result.codes,undefined);x=await call(`/v2/assessments/${aid}/surveys/${sid}/codes/export`,'POST',{mode:'execute'});assert.equal(x.v.error.code,'CONFIRM_REQUIRED');x=await call(`/v2/assessments/${aid}/surveys/${sid}/codes/export`,'POST',{mode:'dry_run'});const token=x.v.result.confirm_token;x=await call(`/v2/assessments/${aid}/surveys/${sid}/codes/export`,'POST',{mode:'execute',confirm_token:token});const code=x.v.result.codes[0].code;cookie='';x=await call('/v2/participate/code','POST',{code});bearer=x.v.result.participant_token;x=await call('/v2/participate/form');assert.equal(x.v.result.items[0].item_id,'demo-context');const submission={answers:[{item_id:'demo-context',value:'Fixture response'}],template_version:1,form_revision:1};x=await call('/v2/participate/responses','POST',submission,{'Idempotency-Key':'once'});assert.equal(x.v.ok,true);const rec=x.v.receipt.id;const trace=x.v.trace_id;x=await call('/v2/participate/responses','POST',submission,{'Idempotency-Key':'once'});assert.equal(x.v.receipt.id,rec);assert.notEqual(x.v.trace_id,trace);x=await call('/v2/participate/responses','POST',{...submission,answers:[{item_id:'demo-context',value:'Changed'}]},{'Idempotency-Key':'once'});assert.equal(x.v.error.code,'IDEMPOTENCY_CONFLICT');x=await call(`/v2/assessments/${aid}/results`);assert.equal(x.r.status,404);x=await call('/mcp','POST',{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'read',arguments:{capability:'cap.response.receipt'}}});assert.equal(JSON.parse(x.v.result.content[0].text).receipt.id,rec);
});
test('local login rejects production, remote host and cross-origin mutation',async()=>{for(const [url,env]of[['http://localhost/v2/dev/session',{APP_ENV:'production'}],['https://public.example/v2/dev/session',{APP_ENV:'local'}]]){const r=await worker.fetch(new Request(url,{method:'POST',headers:{Origin:new URL(url).origin},body:'{}'}),env);assert.equal(r.status,503);}const r=await worker.fetch(new Request('http://localhost/v2/dev/session',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'}),{APP_ENV:'local'});assert.equal(r.status,403);});
