#!/usr/bin/env node
// Release identity stamp (ticket 2026-09-17-3d-release-identity). Node stdlib only; runs from the
// pretypecheck/pretest/predev hooks and via `npm run stamp`.
//
// Authority chain: cookbook release record (immutable commit) -> release/release-manifest.json (pinned copy)
// -> package.json / package-lock.json version (validated here, never authored here) -> src/version.generated.ts
// (git-ignored) -> health / MCP serverInfo / ui/changelog.json (git-ignored, generated from the pinned
// release/cookbook/releases.json copy).
//
// Commit sha: in CI (CI=true or WORKERS_CI=1) WORKERS_CI_COMMIT_SHA is REQUIRED; absent -> exit 1, never a
// fabricated sha. Locally: `git rev-parse HEAD`.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const readJson = (p) => JSON.parse(readFileSync(join(root, p), "utf8"));
const fail = (msg) => { console.error(`stamp-version: ${msg}`); process.exit(1); };

const manifest = readJson("release/release-manifest.json");
const pkg = readJson("package.json");
const lock = readJson("package-lock.json");
const version = manifest.version;
if (typeof version !== "string" || !/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) fail(`manifest version is not semver: ${JSON.stringify(version)}`);
if (pkg.version !== version) fail(`package.json version ${pkg.version} != release manifest version ${version} (the cookbook record is the authority; fix package.json)`);
const lockRoot = lock.packages && lock.packages[""] ? lock.packages[""].version : undefined;
if (lock.version !== version || lockRoot !== version) fail(`package-lock.json versions (${lock.version}, ${lockRoot}) != release manifest version ${version}`);
if (!/^[0-9a-f]{40}$/.test(String(manifest.cookbook_commit))) fail("manifest cookbook_commit is not a 40-hex sha");

const inCI = process.env.CI === "true" || process.env.WORKERS_CI === "1";
let sha;
if (inCI) {
  sha = process.env.WORKERS_CI_COMMIT_SHA ?? "";
  if (!/^[0-9a-f]{40}$/.test(sha)) fail("CI build without a valid 40-hex WORKERS_CI_COMMIT_SHA — refusing to fabricate a commit sha (Workers Builds injects it at build time; check the trigger environment)");
} else {
  try { sha = execFileSync("git", ["rev-parse", "HEAD"], { cwd: root, encoding: "utf8" }).trim(); } catch (e) { fail(`git rev-parse HEAD failed: ${e.message}`); }
  if (!/^[0-9a-f]{40}$/.test(sha)) fail(`git rev-parse HEAD returned a non-sha: ${sha}`);
}
const buildUuid = process.env.WORKERS_CI_BUILD_UUID && process.env.WORKERS_CI_BUILD_UUID.length > 0 ? process.env.WORKERS_CI_BUILD_UUID : null;
const stamp = `${version}+${sha.slice(0, 7)}`;

const ts = `// GENERATED by scripts/stamp-version.mjs — do not edit, do not commit (git-ignored). Import via src/version.ts.
export const APP_VERSION = ${JSON.stringify(version)};
export const APP_COMMIT = ${JSON.stringify(sha)};
export const APP_STAMP = ${JSON.stringify(stamp)};
export const BUILD_UUID: string | null = ${JSON.stringify(buildUuid)};
export const RELEASE_SOURCE = ${JSON.stringify(manifest.cookbook_commit)};
`;

// ui/changelog.json from the pinned releases.json copy: {current, versions:[{version,status,date?,tag?,sections}]} newest-first.
const releases = readJson("release/cookbook/releases.json");
if (releases.current !== version) fail(`pinned releases.json current ${releases.current} != manifest version ${version}`);
const cmp = (a, b) => { const pa = a.split(".").map(Number), pb = b.split(".").map(Number); for (let i = 0; i < 3; i++) if (pa[i] !== pb[i]) return pb[i] - pa[i]; return 0; };
const keys = ["added", "changed", "fixed", "security"];
// Plain text only: reject HTML elements/comments (placeholders like <version>+<sha7> are prose, not markup).
const HTML_TAG = /<\/?(?:script|style|iframe|object|embed|svg|img|a|link|meta|html|body|div|span|p|br|b|i|em|strong|u|ul|ol|li|h[1-6]|table|tr|td|th|form|input|button)(?:[\s>\/])|<!--/i;
const versions = [...releases.versions].sort((a, b) => cmp(a.version, b.version)).map((v) => {
  const sections = {};
  for (const k of keys) {
    const arr = Array.isArray(v.sections?.[k]) ? v.sections[k] : [];
    for (const line of arr) if (typeof line !== "string" || HTML_TAG.test(line)) fail(`release ${v.version} ${k}: entries must be plain text (no HTML)`);
    sections[k] = arr;
  }
  const out = { version: v.version, status: v.status, sections };
  if (v.date) out.date = v.date;
  if (v.tag) out.tag = v.tag;
  return out;
});
const changelog = JSON.stringify({ current: releases.current, versions }, null, 2) + "\n";

const writeIfChanged = (p, content) => { const f = join(root, p); mkdirSync(dirname(f), { recursive: true }); if (existsSync(f) && readFileSync(f, "utf8") === content) return false; writeFileSync(f, content); return true; };
const a = writeIfChanged("src/version.generated.ts", ts);
const b = writeIfChanged("ui/changelog.json", changelog);
console.log(`stamp-version: ${stamp} (release_source ${manifest.cookbook_commit.slice(0, 7)}${buildUuid ? `, build ${buildUuid}` : ""})${a || b ? "" : " — unchanged"}`);
