import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {mountShell} from './tree.js';
import {safeHref} from './core.js';
import {fixture} from '../../test/fixtures/kit-shell-data.js';
function setup(model=fixture()){const d=new JSDOM('<div id="app"></div>',{url:'https://fixture.invalid/'});const root=d.window.document.querySelector('#app');const events=[];const shell=mountShell(root,model,{onNavigate:(...a)=>events.push(a),onAction:(...a)=>events.push(a)});return {d,root,events,shell};}
test('all four models disclose only supplied visible scopes/actions',()=>{for(const role of ['owner','member','viewer','direct']){const {root,shell}=setup(fixture(role));assert.equal(root.querySelectorAll('[data-action]').length,role==='owner'?2:role==='viewer'?0:1);if(['viewer','direct'].includes(role)){assert.ok(!root.textContent.includes('River Valley'));assert.ok(!root.textContent.includes('Field team'));}assert.equal(root.querySelector('nav[aria-label="Scopes"] [aria-current]').textContent.includes('September'),true);assert.ok(!root.textContent.includes('View as'));shell.destroy();}});
test('menu keyboard cycles and Escape returns focus; outside close',()=>{const {root,d}=setup();const toggle=root.querySelector('[data-menu-toggle]');toggle.click();const buttons=root.querySelectorAll('[data-action]');assert.equal(d.window.document.activeElement,buttons[0]);buttons[0].dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.equal(d.window.document.activeElement,buttons[1]);buttons[1].dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.window.document.activeElement,toggle);assert.equal(toggle.getAttribute('aria-expanded'),'false');toggle.click();root.querySelector('h1').click();assert.equal(root.querySelector('[data-menu]').hidden,true);});
test('tree expansion preserves focus and search excludes hidden descendants',()=>{const m=fixture();m.nodes.push({id:'private',label:'Secret',visible:false,children:[{id:'nested',label:'Secret child',visible:true}]});const {root,d}=setup(m);root.querySelector('[data-expand="a1"]').click();assert.equal(root.querySelector('[data-expand="a1"]').getAttribute('aria-expanded'),'false');assert.equal(d.window.document.activeElement,root.querySelector('[data-expand="a1"]'));const input=root.querySelector('[data-search]');input.value='Secret';input.dispatchEvent(new d.window.Event('input',{bubbles:true}));assert.ok(!root.querySelector('[aria-label="Scopes"]').textContent.includes('Secret'));});
test('model update invalidates old bindings, role and callback context',()=>{const {root,shell,events}=setup();const old=root.querySelector('[data-action]');root.querySelector('[data-menu-toggle]').click();shell.update(fixture('viewer'));old.click();assert.equal(events.length,0);assert.ok(!root.textContent.includes('Miriam'));assert.equal(root.querySelector('[data-menu]'),null);root.querySelector('[data-navigate]').click();assert.equal(events[0][1].identity,'viewer');shell.destroy();assert.equal(root.childNodes.length,0);});
test('hostile labels and destinations remain inert',()=>{const m=fixture();m.title='<img src=x onerror=alert(1)>';m.nodes=[{id:'bad" onclick="x',label:'<script>boom</script>',visible:true,href:'javascript:alert(1)'}];m.ancestors=[{label:'Bad',visible:true,href:'//evil.test'}];const {root}=setup(m);assert.equal(root.querySelectorAll('script,img').length,0);assert.ok(root.textContent.includes('<img'));assert.equal(root.querySelector('[href^="javascript"]'),null);assert.equal(root.querySelector('[href^="//"]'),null);assert.equal(safeHref('#assessment/a1/understand'),'#assessment/a1/understand');});
test('navigation and action are callbacks only, original model unmodified',()=>{const m=fixture();const before=JSON.stringify(m);const {root,events,d}=setup(m);root.querySelector('[data-menu-toggle]').click();root.querySelector('[data-action]').click();assert.equal(events[0][0],'people');assert.equal(d.window.location.hash,'');assert.equal(d.window.localStorage.length,0);assert.equal(d.window.sessionStorage.length,0);assert.equal(JSON.stringify(m),before);});
test('unallowed action never appears even with privileged label',()=>{const m=fixture('viewer');m.actions=[{id:'delete',label:'Delete',allowed:false}];const {root}=setup(m);assert.equal(root.querySelector('[data-menu-toggle]'),null);assert.ok(!root.textContent.includes('Delete'));});

test('local tree/search changes preserve mounted content; model update clears it',()=>{const {root,shell,d}=setup();const child=d.window.document.createElement('button');child.textContent='Mounted report';let clicks=0;child.onclick=()=>clicks++;shell.content.append(child);root.querySelector('[data-expand="a1"]').click();assert.equal(shell.content.firstChild,child);child.click();assert.equal(clicks,1);shell.update(fixture('viewer'));assert.equal(shell.content.childNodes.length,0);});
