import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {mountShell} from './tree.js';
import {safeHref} from './core.js';
import {fixture} from '../../test/fixtures/kit-shell-data.js';
import {readFileSync} from 'node:fs';
function setup(model=fixture()){const d=new JSDOM('<div id="app"></div>',{url:'https://fixture.invalid/'});const root=d.window.document.querySelector('#app');const events=[];const shell=mountShell(root,model,{onNavigate:(...a)=>events.push(a),onAction:(...a)=>events.push(a)});return {d,root,events,shell};}
test('shell tests excluded from deployed ui assets; fixtures live outside asset root',()=>{const ignores=readFileSync(new URL('../.assetsignore',import.meta.url),'utf8').split(/\r?\n/);assert.ok(ignores.includes('kit/shell.test.mjs'));for(const file of ['core.js','tree.js','kit.css','tokens.css','components.css'])assert.ok(!ignores.includes('kit/'+file));const config=readFileSync(new URL('../../wrangler.toml',import.meta.url),'utf8');assert.match(config,/\[assets\]\s*directory\s*=\s*"\.\/ui"/);assert.ok(!new URL('../../test/fixtures/kit-shell.html',import.meta.url).pathname.startsWith(new URL('../',import.meta.url).pathname));});
test('all four models disclose only supplied visible scopes/actions',()=>{for(const role of ['owner','member','viewer','direct']){const {root,shell}=setup(fixture(role));assert.equal(root.querySelectorAll('[data-action]').length,role==='owner'?2:role==='viewer'?0:1);if(['viewer','direct'].includes(role)){assert.ok(!root.textContent.includes('River Valley'));assert.ok(!root.textContent.includes('Field team'));}assert.equal(root.querySelector('nav[aria-label="Scopes"] [aria-current]').textContent.includes('September'),true);assert.ok(!root.textContent.includes('View as'));shell.destroy();}});
test('menu keyboard cycles and Escape returns focus; outside close',()=>{const {root,d}=setup();const toggle=root.querySelector('[data-menu-toggle]');toggle.click();const buttons=root.querySelectorAll('[data-action]');assert.equal(d.window.document.activeElement,buttons[0]);buttons[0].dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.equal(d.window.document.activeElement,buttons[1]);buttons[1].dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.window.document.activeElement,toggle);assert.equal(toggle.getAttribute('aria-expanded'),'false');toggle.click();root.querySelector('h1').click();assert.equal(root.querySelector('[data-menu]').hidden,true);});
test('tree expansion preserves focus and search excludes hidden descendants',()=>{const m=fixture();m.nodes.push({id:'private',label:'Secret',visible:false,children:[{id:'nested',label:'Secret child',visible:true}]});const {root,d}=setup(m);root.querySelector('[data-expand="a1"]').click();assert.equal(root.querySelector('[data-expand="a1"]').getAttribute('aria-expanded'),'false');assert.equal(d.window.document.activeElement,root.querySelector('[data-expand="a1"]'));const input=root.querySelector('[data-search]');input.value='Secret';input.dispatchEvent(new d.window.Event('input',{bubbles:true}));assert.ok(!root.querySelector('[aria-label="Scopes"]').textContent.includes('Secret'));});
test('model update invalidates old bindings, role and callback context',()=>{const {root,shell,events}=setup();const old=root.querySelector('[data-action]');root.querySelector('[data-menu-toggle]').click();shell.update(fixture('viewer'));old.click();assert.equal(events.length,0);assert.ok(!root.textContent.includes('Miriam'));assert.equal(root.querySelector('[data-menu]'),null);root.querySelector('[data-navigate]').click();assert.equal(events[0][1].identity,'viewer');shell.destroy();assert.equal(root.childNodes.length,0);});
test('hostile labels and destinations remain inert',()=>{const m=fixture();m.title='<img src=x onerror=alert(1)>';m.nodes=[{id:'bad" onclick="x',label:'<script>boom</script>',visible:true,href:'javascript:alert(1)'}];m.ancestors=[{label:'Bad',visible:true,href:'//evil.test'}];const {root}=setup(m);assert.equal(root.querySelectorAll('script,img').length,0);assert.ok(root.textContent.includes('<img'));assert.equal(root.querySelector('[href^="javascript"]'),null);assert.equal(root.querySelector('[href^="//"]'),null);assert.equal(safeHref('#assessment/a1/understand'),'#assessment/a1/understand');});
test('navigation and action are callbacks only, original model unmodified',()=>{const m=fixture();const before=JSON.stringify(m);const {root,events,d}=setup(m);root.querySelector('[data-menu-toggle]').click();root.querySelector('[data-action]').click();assert.equal(events[0][0],'people');assert.equal(d.window.location.hash,'');assert.equal(d.window.localStorage.length,0);assert.equal(d.window.sessionStorage.length,0);assert.equal(JSON.stringify(m),before);});
test('unallowed action never appears even with privileged label',()=>{const m=fixture('viewer');m.actions=[{id:'delete',label:'Delete',allowed:false}];const {root}=setup(m);assert.equal(root.querySelector('[data-menu-toggle]'),null);assert.ok(!root.textContent.includes('Delete'));});

test('local tree/search changes preserve mounted content; model update clears it',()=>{const {root,shell,d}=setup();const child=d.window.document.createElement('button');child.textContent='Mounted report';let clicks=0;child.onclick=()=>clicks++;shell.content.append(child);root.querySelector('[data-expand="a1"]').click();assert.equal(shell.content.firstChild,child);child.click();assert.equal(clicks,1);shell.update(fixture('viewer'));assert.equal(shell.content.childNodes.length,0);});
test('current assessment fixture grant agrees in header, crumbs, tree and actions',()=>{for(const role of ['owner','member','viewer','direct']){const m=fixture(role);const {root}=setup(m);const current=root.querySelector('[aria-label="Scopes"] [aria-current]').closest('.tree-row');assert.equal(current.querySelector('.tree-role').textContent,m.role);assert.equal(root.querySelector('.crumbs .tree-role').textContent,m.role);assert.ok(root.querySelector('.me').textContent.endsWith(m.role));assert.equal([...root.querySelectorAll('[data-action]')].some(e=>e.textContent==='Rename assessment'),m.role==='Owner');}});

test('IME keeps composing field and content, then filters committed query with selection',()=>{const {root,d,shell}=setup();const field=root.querySelector('[data-search]'),content=d.window.document.createElement('input');content.value='unsaved';shell.content.append(content);field.focus();field.dispatchEvent(new d.window.CompositionEvent('compositionstart',{bubbles:true}));field.value='に';field.dispatchEvent(new d.window.InputEvent('input',{bubbles:true,isComposing:true}));assert.equal(root.querySelector('[data-search]'),field);assert.equal(d.window.document.activeElement,field);field.value='September';field.setSelectionRange(2,5,'backward');field.dispatchEvent(new d.window.InputEvent('input',{bubbles:true,isComposing:false}));assert.equal(root.querySelector('[data-search]'),field);field.dispatchEvent(new d.window.CompositionEvent('compositionend',{bubbles:true}));const committed=root.querySelector('[data-search]');assert.equal(committed.value,'September');assert.equal(committed.selectionStart,2);assert.equal(committed.selectionEnd,5);assert.equal(committed.selectionDirection,'backward');assert.equal(d.window.document.activeElement,committed);assert.equal(shell.content.firstChild,content);assert.equal(content.value,'unsaved');assert.ok(!root.querySelector('[aria-label="Scopes"]').textContent.includes('River Valley'));});
test('isComposing-only input waits for compositionend, cancelled composition restores full tree',()=>{const {root,d}=setup();const field=root.querySelector('[data-search]');field.focus();field.value='仮';field.dispatchEvent(new d.window.InputEvent('input',{bubbles:true,isComposing:true}));assert.equal(root.querySelector('[data-search]'),field);field.value='';field.dispatchEvent(new d.window.CompositionEvent('compositionend',{bubbles:true}));assert.ok(root.querySelector('[aria-label="Scopes"]').textContent.includes('River Valley'));const next=root.querySelector('[data-search]');next.value='September';next.dispatchEvent(new d.window.InputEvent('input',{bubbles:true}));assert.ok(!root.querySelector('[aria-label="Scopes"]').textContent.includes('River Valley'));});
test('stale composition cannot restore prior model after identity replacement or destroy',()=>{for(const destroy of [false,true]){const {root,d,shell}=setup();const field=root.querySelector('[data-search]');field.dispatchEvent(new d.window.CompositionEvent('compositionstart',{bubbles:true}));field.value='Miriam';if(destroy)shell.destroy();else shell.update(fixture('viewer'));field.dispatchEvent(new d.window.CompositionEvent('compositionend',{bubbles:true}));field.dispatchEvent(new d.window.InputEvent('input',{bubbles:true}));if(destroy)assert.equal(root.childNodes.length,0);else{assert.equal(root.querySelector('[data-search]').value,'');assert.ok(!root.textContent.includes('Miriam'));assert.ok(!root.textContent.includes('Field team'));}}});
test('composition commit preserves outside focus and the intended pressed row',()=>{for(const targetKind of ['row','content']){const {root,d,shell,events}=setup();const input=root.querySelector('[data-search]');const child=d.window.document.createElement('input');child.value='unsaved';shell.content.append(child);const target=targetKind==='row'?root.querySelector('[aria-label="Scopes"] [data-navigate]'):child;const href=target.dataset.navigate;input.focus();input.dispatchEvent(new d.window.CompositionEvent('compositionstart',{bubbles:true}));input.value='September';target.dispatchEvent(new d.window.Event('pointerdown',{bubbles:true}));input.dispatchEvent(new d.window.CompositionEvent('compositionend',{bubbles:true}));target.focus();input.dispatchEvent(new d.window.InputEvent('input',{bubbles:true}));target.click();assert.equal(target.isConnected,true);assert.equal(d.window.document.activeElement,target);assert.equal(root.querySelector('[data-search]'),input);assert.equal(shell.content.firstChild,child);assert.equal(child.value,'unsaved');if(href)assert.equal(events[0][0],href);input.focus();assert.ok(!root.querySelector('[aria-label="Scopes"]').textContent.includes('River Valley'));assert.equal(d.window.document.activeElement,input);}});
test('keyboard blur commit does not steal focus and deferred work cannot revive old identity',()=>{for(const destroy of [false,true]){const {root,d,shell}=setup();const input=root.querySelector('[data-search]'),target=root.querySelector('[data-menu-toggle]');input.focus();input.dispatchEvent(new d.window.CompositionEvent('compositionstart',{bubbles:true}));input.value='Miriam';target.focus();input.dispatchEvent(new d.window.CompositionEvent('compositionend',{bubbles:true}));assert.equal(d.window.document.activeElement,target);if(destroy)shell.destroy();else shell.update(fixture('viewer'));input.dispatchEvent(new d.window.FocusEvent('focusin',{bubbles:true}));input.dispatchEvent(new d.window.CompositionEvent('compositionend',{bubbles:true}));assert.equal(input.isConnected,false);if(destroy)assert.equal(root.childNodes.length,0);else{assert.equal(root.querySelector('[data-search]').value,'');assert.ok(!root.textContent.includes('Miriam'));}}});

test('composition commit followed by caret click retains committed query through repaint',()=>{const {root,d,shell}=setup();const input=root.querySelector('[data-search]'),caret=root.querySelector('[data-expand="a1"]');const content=d.window.document.createElement('input');content.value='kept';shell.content.append(content);input.focus();input.dispatchEvent(new d.window.CompositionEvent('compositionstart',{bubbles:true}));input.value='September';caret.dispatchEvent(new d.window.Event('pointerdown',{bubbles:true}));input.dispatchEvent(new d.window.CompositionEvent('compositionend',{bubbles:true}));caret.focus();input.dispatchEvent(new d.window.InputEvent('input',{bubbles:true}));caret.click();assert.equal(root.querySelector('[data-search]').value,'September');assert.equal(d.window.document.activeElement,root.querySelector('[data-expand="a1"]'));assert.equal(root.querySelector('[data-expand="a1"]').getAttribute('aria-expanded'),'false');assert.ok(root.querySelector('[aria-label="Scopes"]').textContent.includes('River Valley'));assert.equal(shell.content.firstChild,content);assert.equal(content.value,'kept');root.querySelector('[data-search]').focus();assert.ok(!root.querySelector('[aria-label="Scopes"]').textContent.includes('River Valley'));assert.ok(root.querySelector('[aria-label="Scopes"]').textContent.includes('September'));});

test('local repaint preserves delegated mount root; update and destroy detach old controls',()=>{for(const destroy of [false,true]){const {root,d,shell}=setup();const mount=shell.content,button=d.window.document.createElement('button');button.textContent='Open';mount.append(button);let calls=0;mount.addEventListener('click',e=>{if(mount.contains(e.target))calls++;});button.click();assert.equal(calls,1);root.querySelector('[data-expand="a1"]').click();assert.equal(shell.content,mount);button.click();assert.equal(calls,2);root.querySelector('[data-search]').value='September';root.querySelector('[data-search]').dispatchEvent(new d.window.InputEvent('input',{bubbles:true}));assert.equal(shell.content,mount);button.click();assert.equal(calls,3);if(destroy)shell.destroy();else shell.update(fixture('viewer'));assert.equal(mount.childNodes.length,0);button.click();assert.equal(calls,3);assert.equal(button.isConnected,false);}});

test('search label or icon pointer does not defer a commit that stays in search',()=>{for(const selector of ['.tree-search','.tree-search span']){const {root,d}=setup();const input=root.querySelector('[data-search]');input.focus();input.dispatchEvent(new d.window.CompositionEvent('compositionstart',{bubbles:true}));input.value='September';root.querySelector(selector).dispatchEvent(new d.window.Event('pointerdown',{bubbles:true}));input.dispatchEvent(new d.window.CompositionEvent('compositionend',{bubbles:true}));assert.equal(d.window.document.activeElement,input);assert.ok(!root.querySelector('[aria-label="Scopes"]').textContent.includes('River Valley'));input.value='River';input.dispatchEvent(new d.window.InputEvent('input',{bubbles:true}));assert.ok(root.querySelector('[aria-label="Scopes"]').textContent.includes('River Valley'));assert.ok(!root.querySelector('[aria-label="Scopes"]').textContent.includes('September'));}});

// K3a stable-host interface: real app controls live in the header host and the content mount keeps its element identity.
test('header host and content element keep identity across local paint and model update; host children survive, content children cleared',()=>{const {root,d,shell}=setup();const host=shell.headerHost,content=shell.content;assert.ok(host);const who=d.window.document.createElement('span');who.id='who';who.textContent='Account: private@example.invalid';host.append(who);const view=d.window.document.createElement('p');view.textContent='view';content.append(view);root.querySelector('[data-expand="a1"]').click();assert.equal(shell.headerHost,host);assert.equal(shell.content,content);assert.equal(who.isConnected,true);assert.equal(view.isConnected,true);root.querySelector('[data-search]').value='Sept';root.querySelector('[data-search]').dispatchEvent(new d.window.InputEvent('input',{bubbles:true}));assert.equal(shell.headerHost,host);assert.equal(who.parentNode,host);shell.update(fixture('viewer'));assert.equal(shell.headerHost,host);assert.equal(shell.content,content);assert.equal(who.isConnected,true);assert.equal(view.isConnected,false);assert.equal(content.childNodes.length,0);assert.equal(root.querySelectorAll('[data-header-host]').length,1);assert.equal(root.querySelectorAll('[data-content]').length,1);shell.destroy();assert.equal(root.childNodes.length,0);});
test('header host is empty safe DOM: model text never renders into it',()=>{const m=fixture();m.identityLabel='<b>x</b>';const {root,shell}=setup(m);assert.equal(shell.headerHost.childNodes.length,0);assert.equal(root.querySelector('.header-host b'),null);});
