import {esc} from './core.js';
import {mountView,cards,fields,heading} from './views-coordinator.js';
export const screens=['welcome','tour','example','signin','help','status','trace'];
const ids=new Set(['navigation','start-signin','tour-next','tour-back']);
export function mountPublicView(root,model,onIntent){return mountView(root,model,onIntent,screens,ids,(m,{actions,button})=>{
 const controls=()=>`<div class="row">${actions().map(a=>button(a)).join('')}</div>`;
 if(m.screen==='welcome')return `<section class="glass" style="max-width:var(--stage-max-w);margin:24px auto;padding:var(--stage-pad);border-radius:var(--r-stage);box-shadow:var(--shadow-stage)"><div class="row">${actions().slice(0,1).map(a=>button(a)).join('')}</div>${heading(m)}<div class="three" style="gap:var(--gap-perspectives);margin:30px 0">${(m.perspectives||[]).map((p,i)=>`<article class="rw-perspective"><span class="rw-dot" style="background:var(--${['perspective-team','perspective-community','perspective-church'][i%3]})"></span><h3>${esc(p.label)}</h3><p class="muted" style="font-size:13px">${esc(p.text)}</p></article>`).join('')}</div><div class="row">${actions().slice(1).map(a=>button(a)).join('')}</div>${(m.sections||[]).map(s=>`<details><summary>${esc(s.title)}</summary><p>${esc(s.text)}</p></details>`).join('')}</section>`;
 if(m.screen==='tour'){const steps=m.steps||[],index=m.stepIndex;if(!Number.isInteger(index)||index<0||index>=steps.length)return '<p class="note">Tour step unavailable.</p>';const s=steps[index];return `<section class="glass panel">${heading(m)}<div class="progress">${steps.map((_,i)=>`<span class="${i<=index?'done':''}"></span>`).join('')}</div><p class="eyebrow">Step ${index+1} of ${steps.length}</p><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p><div class="note">${esc(s.example)}</div><div class="row">${actions().filter(a=>a.id!=='tour-back'||index>0).filter(a=>a.id!=='tour-next'||index<steps.length-1).map(a=>button(a)).join('')}</div></section>`;}
 if(m.screen==='signin')return `<section class="glass panel" style="max-width:560px">${m.identity?.confirmed===true?`<p class="note">${esc(m.identity.label)}</p>`:''}${fields(m)}${controls()}</section>`;
 return `${controls()}<div class="grid">${cards(m.items)}</div>${(m.sections||[]).map(s=>`<section class="glass panel"><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p></section>`).join('')}<div data-slot="report"></div>`;
 });}
