import registry from '../contract/capabilities.json' with { type: 'json' };
const uid=()=>crypto.randomUUID();
const now=()=>Math.floor(Date.now()/1000);
class Failure extends Error {constructor(code,status=400){super(code);this.code=code;this.status=status;}}
const fail=(code,status)=>{throw new Failure(code,status)};
const clean=(v,max=160)=>typeof v==='string'&&v.trim()&&v.length<=max?v.trim():fail('INVALID_PARAMS');
const cookie=(r,name)=>r.headers.get('Cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1);
const one=(db,sql,...args)=>db.prepare(sql).bind(...args).first();
const all=async(db,sql,...args)=>(await db.prepare(sql).bind(...args).all()).results;
const run=(db,sql,...args)=>db.prepare(sql).bind(...args).run();
const stmt=(db,sql,...args)=>db.prepare(sql).bind(...args);
const meta=id=>registry.capabilities.find(c=>c.id===id);
export function checkOrigin(request,env={}){const origin=request.headers.get('Origin');if(!['GET','HEAD','OPTIONS'].includes(request.method)&&!origin&&(request.headers.get('Cookie')?.includes('review_session=')||new URL(request.url).pathname==='/v2/dev/session'))fail('ORIGIN_REQUIRED',403);if(!['GET','HEAD','OPTIONS'].includes(request.method)&&origin&&origin!==new URL(request.url).origin&&!(env.APP_ENV==='local'&&origin===env.PUBLIC_ORIGIN))fail('ORIGIN_NOT_ALLOWED',403);}
export function checkTool(tool,capability){const m=meta(capability);if(!m)fail('INVALID_PARAMS');if(tool!==m.tool)fail('WRONG_TOOL_FOR_CLASS');}
const templates=[{id:'synthetic-demo',name:'Synthetic integration questionnaire',version:1,synthetic:true,source_status:'INTEGRATION_FIXTURE_NOT_AUTHORITATIVE_INSTRUMENT',items:[{id:'demo-context',item_id:'demo-context',label:'What helped this synthetic project?',prompt:'What helped this synthetic project?',kind:'text',type:'text',required:true,options:[]}]}];
async function authenticate(request,env){
 const bearer=request.headers.get('Authorization')?.replace(/^Bearer /i,'');
 if(bearer){const p=await one(env.DB,'SELECT p.* FROM participants p JOIN access_codes c ON c.id=p.access_id WHERE p.token=? AND c.revoked=0',bearer);if(p)return{actor:p.id,participant:p};fail('NOT_AUTHENTICATED',401);}
 const token=cookie(request,'review_session');if(token){const s=await one(env.DB,'SELECT * FROM sessions WHERE token=? AND expires_at>?',token,now());if(s)return{actor:s.actor};}
 return null;
}
function need(context){if(!context)fail('NOT_AUTHENTICATED',401);return context;}
async function grant(env,context,type,id,write=false){need(context);const g=await one(env.DB,'SELECT role FROM grants WHERE actor=? AND scope_type=? AND scope_id=?',context.actor,type,id);if(!g)fail('NOT_FOUND_OR_NOT_VISIBLE',404);if(write&&!['owner','member'].includes(g.role))fail('NOT_AUTHORIZED_AT_SCOPE',403);return g;}
async function surveyGrant(env,c,id,write=false){const s=await one(env.DB,'SELECT * FROM surveys WHERE id=?',id);if(!s)fail('NOT_FOUND_OR_NOT_VISIBLE',404);await grant(env,c,'assessment',s.assessment_id,write);return s;}
function receipt(cap,c,trace,inverse='none'){return{id:uid(),actor:c.actor,scope:{type:'assessment',id:c.scope||'session'},class:meta(cap)?.class||'write.reversible',trace_id:trace,at:new Date().toISOString(),inverse};}
export async function execute(cap,p,c,env,trace){
 const done=(result,rec)=>({ok:true,capability:cap,result,...(rec?{receipt:rec}:{}),trace_id:trace});
 const write=result=>done(result,receipt(cap,c,trace));
 if(cap==='cap.ops.health')return done({status:'ok',storage:'D1',auth:env.APP_ENV==='local'?'LOCAL_SYNTHETIC_ONLY':'AUTH_NOT_CONFIGURED'});
 if(cap==='cap.docs.capabilities')return done(registry);
 if(cap==='cap.docs.get')return done({tools:['docs','read','write','danger'],capabilities:registry.capabilities.map(x=>({id:x.id,tool:x.tool})),implementation:'synthetic integration slice; unspecified operations return 501'});
 if(cap==='cap.entry.intents')return done({intents:['what','how','example','take survey','manage','view results']});
 if(cap==='cap.auth.me'){need(c);return done({id:c.actor,principal_id:c.actor,synthetic:true,grants:c.participant?[]:await all(env.DB,'SELECT scope_type,scope_id,role FROM grants WHERE actor=?',c.actor)});}
 if(cap==='cap.template.list'){need(c);return done({items:templates.map(t=>({...t,template_id:t.id,template_version:t.version})),templates:templates.map(t=>({...t,template_id:t.id,template_version:t.version}))});}
 if(cap==='cap.project.create'){need(c);if(c.actor!=='synthetic-facilitator')fail('NOT_AUTHORIZED_AT_SCOPE',403);const id=uid(),name=clean(p.name);await env.DB.batch([stmt(env.DB,'INSERT INTO projects(id,name) VALUES(?,?)',id,name),stmt(env.DB,"INSERT INTO grants VALUES(?,'project',?,'owner')",c.actor,id)]);return write({id,project_id:id,name,synthetic:true});}
 if(cap==='cap.project.list'){need(c);const items=(await all(env.DB,"SELECT p.* FROM projects p JOIN grants g ON g.scope_id=p.id AND g.scope_type='project' WHERE g.actor=?",c.actor)).map(x=>({...x,project_id:x.id}));return done({items,projects:items});}
 if(cap==='cap.assessment.create'){await grant(env,c,'project',p.project_id,true);const id=uid(),name=clean(p.name);let language_id=p.language_id;if(language_id){if(!await one(env.DB,'SELECT id FROM languages WHERE id=? AND project_id=?',language_id,p.project_id))fail('INVALID_PARAMS');}else{language_id=uid();await run(env.DB,'INSERT INTO languages(id,project_id,label,code) VALUES(?,?,?,?)',language_id,p.project_id,clean(p.language?.new?.label),p.language?.new?.code?clean(p.language.new.code):null);}await env.DB.batch([stmt(env.DB,'INSERT INTO assessments(id,project_id,name,language_id) VALUES(?,?,?,?)',id,p.project_id,name,language_id),stmt(env.DB,"INSERT INTO grants VALUES(?,'assessment',?,'owner')",c.actor,id)]);return write({id,assessment_id:id,project_id:p.project_id,name,language_id,stage:'prepare',revision:1,synthetic:true});}
 if(cap==='cap.assessment.get'){await grant(env,c,'assessment',p.assessment_id);const a=await one(env.DB,'SELECT * FROM assessments WHERE id=?',p.assessment_id);return done({...a,assessment_id:a.id,surveys:await all(env.DB,'SELECT * FROM surveys WHERE assessment_id=?',a.id)});}
 if(cap==='cap.assessment.set_stage'){await grant(env,c,'assessment',p.assessment_id,true);if(!['prepare','collect','understand','improve'].includes(p.stage))fail('INVALID_PARAMS');const prior=await one(env.DB,'SELECT revision FROM assessments WHERE id=?',p.assessment_id);if(p.expected_revision!==undefined&&p.expected_revision!==prior.revision)fail('PRECONDITION_FAILED',409);const changed=await run(env.DB,'UPDATE assessments SET stage=?,revision=revision+1 WHERE id=? AND revision=?',p.stage,p.assessment_id,prior.revision);if((changed.meta?.changes??changed.changes)!==1)fail('PRECONDITION_FAILED',409);return write({id:p.assessment_id,assessment_id:p.assessment_id,stage:p.stage,revision:prior.revision+1});}
 if(cap==='cap.survey.select'){await grant(env,c,'assessment',p.assessment_id,true);const t=templates.find(x=>x.id===p.template_id);if(!t||(p.template_version!==undefined&&p.template_version!==t.version))fail('INVALID_PARAMS');const id=uid();await run(env.DB,'INSERT INTO surveys(id,assessment_id,template_id) VALUES(?,?,?)',id,p.assessment_id,t.id);return write({id,assessment_survey_id:id,assessment_id:p.assessment_id,template_id:t.id,template_version:1});}
 if(cap==='cap.survey.issue_codes'){const scopedSurvey=await surveyGrant(env,c,p.survey_id,true);if(p.assessment_id&&p.assessment_id!==scopedSurvey.assessment_id)fail('NOT_FOUND_OR_NOT_VISIBLE',404);const count=p.count??1;if(!Number.isInteger(count)||count<1||count>30)fail('INVALID_PARAMS');const batch_id=uid();const codes=Array.from({length:count},()=>({id:uid(),code:uid().replaceAll('-','').slice(0,16).toUpperCase()}));await env.DB.batch(codes.map(x=>stmt(env.DB,'INSERT INTO access_codes(id,survey_id,code,batch_id) VALUES(?,?,?,?)',x.id,p.survey_id,x.code,batch_id)));return write({count,ids:codes.map(x=>x.id),batch_id});}
 if(cap==='cap.survey.export_codes'){const scopedSurvey=await surveyGrant(env,c,p.survey_id,true);if(p.assessment_id&&p.assessment_id!==scopedSurvey.assessment_id)fail('NOT_FOUND_OR_NOT_VISIBLE',404);if(p.mode==='dry_run'){const id=uid();const selected=await all(env.DB,'SELECT id FROM access_codes WHERE survey_id=? AND revoked=0 AND (? IS NULL OR batch_id=?)',p.survey_id,p.batch_id??null,p.batch_id??null);await run(env.DB,'INSERT INTO intents(id,actor,survey_id,expires_at,code_ids,batch_id) VALUES(?,?,?,?,?,?)',id,c.actor,p.survey_id,now()+300,JSON.stringify(selected.map(x=>x.id)),p.batch_id??null);return done({impact:{effect:'credential_disclosure',survey_id:p.survey_id,count:(await one(env.DB,'SELECT count(*) n FROM access_codes WHERE survey_id=? AND revoked=0',p.survey_id)).n},confirm_token:id,expires_in:300,policy:'synthetic-demo-proposed'});}
 if(p.mode!=='execute'||!p.confirm_token)fail('CONFIRM_REQUIRED');const intent=await one(env.DB,'SELECT * FROM intents WHERE id=? AND actor=? AND survey_id=?',p.confirm_token,c.actor,p.survey_id);if(!intent||intent.expires_at<now()||(intent.batch_id!==null&&intent.batch_id!==p.batch_id))fail('CONFIRM_EXPIRED');const selectedIds=new Set(JSON.parse(intent.code_ids));const codes=(await all(env.DB,'SELECT id,code FROM access_codes WHERE survey_id=? AND revoked=0',p.survey_id)).filter(x=>selectedIds.has(x.id));if(codes.length!==selectedIds.size)fail('PRECONDITION_FAILED',409);const rec=intent.receipt?JSON.parse(intent.receipt):receipt(cap,c,trace);await run(env.DB,'UPDATE intents SET receipt=COALESCE(receipt,?) WHERE id=?',JSON.stringify(rec),intent.id);return done({codes,synthetic:true},rec);}
 if(cap==='cap.participant.redeem_code'){const code=clean(p.code).toUpperCase();const a=await one(env.DB,'SELECT * FROM access_codes WHERE code=? AND revoked=0',code);if(!a)fail('NOT_AUTHENTICATED',401);await run(env.DB,'INSERT OR IGNORE INTO participants(id,survey_id,access_id,token) VALUES(?,?,?,?)',uid(),a.survey_id,a.id,uid());const participant=await one(env.DB,'SELECT * FROM participants WHERE access_id=?',a.id);return done({participant_token:participant.token,participant_id:participant.id,assessment_survey_id:a.survey_id});}
 if(cap==='cap.response.form'||cap==='cap.response.receipt'||cap==='cap.response.submit'){need(c);if(!c.participant)fail('NOT_AUTHORIZED_AT_SCOPE',403);const part=c.participant;const s=await one(env.DB,'SELECT s.*,a.stage FROM surveys s JOIN assessments a ON a.id=s.assessment_id WHERE s.id=?',part.survey_id);const prior=await one(env.DB,'SELECT * FROM submissions WHERE participant_id=?',part.id);
 if(cap==='cap.response.receipt'){if(!prior)fail('NOT_FOUND_OR_NOT_VISIBLE',404);return done({submitted:true,response_id:prior.id,submitted_at:JSON.parse(prior.receipt).at},JSON.parse(prior.receipt));}
 if(cap==='cap.response.form')return done({participant_id:part.id,assessment_survey_id:s.id,template_id:s.template_id,template:templates.find(t=>t.id===s.template_id),items:templates.find(t=>t.id===s.template_id).items,template_version:1,form_revision:1,submitted:!!prior,stage:s.stage});
 const key=clean(p.idempotency_key,200);if(!p.answers||typeof p.answers!=='object')fail('INVALID_PARAMS');const answer=clean(Array.isArray(p.answers)?p.answers.find(x=>x.item_id==='demo-context')?.value:p.answers['demo-context'],2000);if(p.template_version!==undefined&&p.template_version!==1)fail('INVALID_PARAMS');if(p.form_revision!==undefined&&p.form_revision!==1)fail('INVALID_PARAMS');const answers=JSON.stringify({'demo-context':answer});
 if(prior){if(prior.idempotency_key!==key||prior.answers!==answers)fail('IDEMPOTENCY_CONFLICT',409);return done({submitted:true,response_id:prior.id,submitted_at:JSON.parse(prior.receipt).at},JSON.parse(prior.receipt));}
 if(s.stage!=='collect')fail('STAGE_CONFLICT',409);const id=uid(),rec=receipt(cap,c,trace);await run(env.DB,'INSERT OR IGNORE INTO submissions(id,participant_id,survey_id,answers,digest,idempotency_key,receipt) VALUES(?,?,?,?,?,?,?)',id,part.id,s.id,answers,answers,key,JSON.stringify(rec));const saved=await one(env.DB,'SELECT * FROM submissions WHERE participant_id=?',part.id);if(saved.answers!==answers||saved.idempotency_key!==key)fail('IDEMPOTENCY_CONFLICT',409);return done({submitted:true,response_id:saved.id,submitted_at:JSON.parse(saved.receipt).at},JSON.parse(saved.receipt));}
 if(cap==='cap.results.summary'){await grant(env,c,'assessment',p.assessment_id);const n=await one(env.DB,'SELECT count(*) n FROM submissions r JOIN surveys s ON s.id=r.survey_id WHERE s.assessment_id=?',p.assessment_id);return done({synthetic:true,submission_count:n.n,synthetic_submission_count:n.n,scoring_status:'POLICY_PENDING',policy_held:true,suppressed:true,policy_state:'D7_AND_SCORING_HOLDS',message:'Synthetic integration counts only. No authoritative scores or private results.'});}
 fail('RESERVED_NOT_BUILT',501);
}
function route(method,path){const direct={'GET /v2/health':'cap.ops.health','GET /v2/me':'cap.auth.me','GET /v2/templates':'cap.template.list','GET /v2/projects':'cap.project.list','POST /v2/projects':'cap.project.create','POST /v2/participate/code':'cap.participant.redeem_code','GET /v2/participate/form':'cap.response.form','POST /v2/participate/responses':'cap.response.submit','GET /v2/participate/receipt':'cap.response.receipt','GET /v2/docs':'cap.docs.get','GET /v2/entry':'cap.entry.intents','GET /v2/capabilities.json':'cap.docs.capabilities'};if(direct[method+' '+path])return[direct[method+' '+path],{}];
 let m;if(method==='POST'&&(m=path.match(/^\/v2\/projects\/([^/]+)\/assessments$/)))return['cap.assessment.create',{project_id:m[1]}];
 if((m=path.match(/^\/v2\/assessments\/([^/]+)(?:\/(stage|surveys|results))?$/))){const action=method==='GET'?(m[2]==='results'?'cap.results.summary':!m[2]?'cap.assessment.get':null):method==='POST'?(m[2]==='stage'?'cap.assessment.set_stage':m[2]==='surveys'?'cap.survey.select':null):null;if(action)return[action,{assessment_id:m[1]}];}
 if(method==='POST'&&(m=path.match(/^\/v2\/assessments\/([^/]+)\/surveys\/([^/]+)\/codes(\/export)?$/)))return[m[3]?'cap.survey.export_codes':'cap.survey.issue_codes',{assessment_id:m[1],survey_id:m[2]}];
 return null;
}
export default {async fetch(request,env){const trace=uid(),headers={'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};try{checkOrigin(request,env);const url=new URL(request.url);const body=['POST','PATCH','PUT','DELETE'].includes(request.method)?await request.json().catch(()=>({})):{};
 if(url.pathname==='/v2/dev/session'&&request.method==='POST'){if(env.APP_ENV!=='local'||!['127.0.0.1','localhost','[::1]'].includes(url.hostname))fail('AUTH_NOT_CONFIGURED',503);const token=uid();await run(env.DB,'INSERT INTO sessions VALUES(?,?,?)',token,'synthetic-facilitator',now()+3600);headers['Set-Cookie']=`review_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=3600${url.protocol==='https:'?'; Secure':''}`;return Response.json({ok:true,capability:'dev.session',result:{id:'synthetic-facilitator',synthetic:true},trace_id:trace},{headers});}
 if(url.pathname.startsWith('/v2/auth/'))fail('AUTH_NOT_CONFIGURED',503);
 const c=await authenticate(request,env);
 if(url.pathname==='/mcp'&&request.method==='POST'){if(body.method==='initialize')return Response.json({jsonrpc:'2.0',id:body.id,result:{protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:'3d-review-integration',version:'0.1.0'}}},{headers});if(body.method==='notifications/initialized')return new Response(null,{status:202});if(body.method==='tools/list')return Response.json({jsonrpc:'2.0',id:body.id,result:{tools:['docs','read','write','danger'].map(name=>({name,description:'Shared capability handler',inputSchema:{type:'object',properties:{capability:{type:'string'},params:{type:'object'},mode:{type:'string'},confirm_token:{type:'string'}}}}))}},{headers});if(body.method!=='tools/call')fail('INVALID_PARAMS');const {name,arguments:a={}}=body.params||{};const cap=a.capability||(name==='docs'?'cap.docs.get':null);if(name!=='docs')checkTool(name,cap);else if(cap!=='cap.docs.get')fail('WRONG_TOOL_FOR_CLASS');let result;try{result=await execute(cap,{...a.params,...(a.idempotency_key?{idempotency_key:a.idempotency_key}:{}),...(a.mode?{mode:a.mode}:{}),...(a.confirm_token?{confirm_token:a.confirm_token}:{})},c,env,trace);}catch(e){result={ok:false,error:{code:e.code||'INTERNAL_ERROR'},trace_id:trace};}return Response.json({jsonrpc:'2.0',id:body.id,result:{content:[{type:'text',text:JSON.stringify(result)}],isError:!result.ok}},{headers});}
 const r=route(request.method,url.pathname);if(!r)fail('NOT_FOUND_OR_NOT_VISIBLE',404);return Response.json(await execute(r[0],{...body,idempotency_key:request.headers.get('Idempotency-Key')||body.idempotency_key,...r[1]},c,env,trace),{headers});
 }catch(e){return Response.json({ok:false,error:{code:e.code||'INTERNAL_ERROR',message:e.code||'Request failed'},trace_id:trace},{status:e.status||500,headers});}}};
