#!/usr/bin/env python3
"""seed/synthetic/answer-sets.json (Steve's persona generator, pinned) → seed/synthetic-responses.sql

Loads the synthetic projects as real rows: project + language (+ owner grants for the seeded demo owner) →
one assessment per rendered cycle (stage 'understand', so results are readable) → one assessment_survey per
form used → one response per submission, answers as option CODES exactly as cap.response.submit stores them
(validated against the v2 template items in migrations/0004). source='synthetic', provenance names the persona.
Apply AFTER migrations 0001–0004 and seed/synthetic.sql. Idempotent (INSERT OR IGNORE).
"""
import json, re, hashlib, sys, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# usage: synth_seed_sql.py [dataset]  — named-personas (default, output unchanged) | org-comparison
DATASET = sys.argv[1] if len(sys.argv) > 1 else "named-personas"
INFILE, OUTSQL, GEN = {"named-personas": ("answer-sets.json", "synthetic-responses.sql", "survey-pipeline/run_synthetic_pipeline.py"),
                       "org-comparison": ("answer-sets-org-comparison.json", "synthetic-responses-org.sql", "survey-pipeline/run_org_comparison_pipeline.py _render(3)")}[DATASET]
recs = json.load(open(f"{root}/seed/synthetic/{INFILE}"))
sql = open(f"{root}/migrations/0004_pinned_instruments.sql").read()
tpl = {}
for m in re.finditer(r"VALUES \('(tpl_[a-z_]*)', 2, '([^']*)', '[^']*', '[^']*', '(\[.*?\])', '(\{.*?\})', ", sql, re.S):
    items = json.loads(m.group(3).replace("''", "'"))
    tpl[m.group(2)] = {"id": m.group(1), "items": {i["id"]: i for i in items}}
OWNER, WS, AT = "person_mara", "ws_cedar", "2026-09-16T12:00:00.000Z"
q = lambda s: "'" + str(s).replace("'", "''") + "'"
out = [f"-- Generated by tools/synth_seed_sql.py from seed/synthetic/{INFILE} (klappy/3d-quality-review@f042cde persona generator). Do not hand-edit.",
       "-- Synthetic projects/languages/assessments/responses for the demo; owner grants go to the seeded demo owner."]
projects, langs, assess, surveys, responses, grants, skipped = {}, {}, {}, {}, [], [], {}
for r in recs:
    pid = "proj_syn_" + r["project_id"]; lid = "lang_syn_" + r["language_id"]; aid = "assess_syn_" + r["assessment_cycle"]
    name = r["project_id"].replace("-", " ").title()
    projects[pid] = f"INSERT OR IGNORE INTO project (id,workspace_id,name,organization,created_at,created_by) VALUES ({q(pid)},{q(WS)},{q(name + ' (synthetic)')},'Synthetic persona org',{q(AT)},{q(OWNER)});"
    langs[lid] = f"INSERT OR IGNORE INTO language (id,project_id,code,name,created_at) VALUES ({q(lid)},{q(pid)},'qaa',{q(name + ' language (invented)')},{q(AT)});"
    cycle = r["assessment_cycle"].rsplit("-", 2)[-2] + "-" + r["assessment_cycle"].rsplit("-", 1)[-1]
    assess[aid] = f"INSERT OR IGNORE INTO assessment (id,project_id,language_id,name,purpose,period,format,stage,created_at,created_by) VALUES ({q(aid)},{q(pid)},{q(lid)},{q(name + ' — cycle ' + cycle)},'Synthetic persona cycle (Steve Watters generator)',{q(cycle)},'written','understand',{q(AT)},{q(OWNER)});"
    t = tpl[r["form_variant"]]; sid = f"survey_syn_{r['assessment_cycle']}_{t['id'][4:]}"
    surveys[sid] = f"INSERT OR IGNORE INTO assessment_survey (id,assessment_id,template_id,template_version,state,collection_status,created_at) VALUES ({q(sid)},{q(aid)},{q(t['id'])},2,'selected','closed',{q(AT)});"
    answers = {}
    for item_id, a in r["answers"].items():
        it = t["items"].get(item_id)
        if not it: skipped[f"{r['form_variant']}:{item_id}"] = skipped.get(f"{r['form_variant']}:{item_id}", 0) + 1; continue
        codes = []
        for text in a["selected"]:
            o = next((o for o in it.get("options", []) if o["text"] == text), None)
            if o: codes.append(o["code"])
            elif it["type"] == "text": codes.append(text)
            else: skipped[f"{item_id}:{text[:30]}"] = skipped.get(f"{item_id}:{text[:30]}", 0) + 1
        if not codes: continue
        answers[item_id] = codes if it["type"] == "multi" else codes[0]
    for item_id, it in t["items"].items():  # required-and-unanswered → the submit validator would refuse; keep honest by marking optional-null only
        if item_id not in answers and it.get("required") is False: answers[item_id] = None
    rid = "resp_syn_" + hashlib.sha256(r["submission_id"].encode()).hexdigest()[:20]
    prov = json.dumps({"generator": f"klappy/3d-quality-review@f042cde {GEN}", "persona": r["respondent_persona"], "submission_id": r["submission_id"], "synthetic": True})
    responses.append(f"INSERT OR IGNORE INTO response (id,assessment_survey_id,respondent_id,idempotency_key,answers_json,template_id,template_version,provenance_json,source,submitted_at) VALUES ({q(rid)},{q(sid)},{q('rsp_' + r['respondent_persona'])},{q(r['submission_id'])},{q(json.dumps(answers))},{q(t['id'])},2,{q(prov)},'synthetic',{q(r['submitted_at'])});")
for pid in projects: grants.append(f"INSERT OR IGNORE INTO \"grant\" (id,principal_id,scope_type,scope_id,role,created_at) VALUES ({q('grant_syn_' + pid)},{q(OWNER)},'project',{q(pid)},'owner',{q(AT)});")
for aid in assess: grants.append(f"INSERT OR IGNORE INTO \"grant\" (id,principal_id,scope_type,scope_id,role,created_at) VALUES ({q('grant_syn_' + aid)},{q(OWNER)},'assessment',{q(aid)},'owner',{q(AT)});")
out += list(projects.values()) + list(langs.values()) + list(assess.values()) + list(surveys.values()) + grants + responses
open(f"{root}/seed/{OUTSQL}", "w").write("\n".join(out) + "\n")
print(json.dumps({"projects": len(projects), "languages": len(langs), "assessments": len(assess), "surveys": len(surveys), "responses": len(responses), "grants": len(grants), "skipped": skipped}, indent=1))
