const $ = (id) => document.getElementById(id);
const state = { assessment:null, survey:null, templates:[], participant:null, form:null, answers:[], batch:null, intent:null, submitted:false };
const keys = new Map();
let busy = false;
function keyFor(path, body) { const fingerprint = `${path}:${JSON.stringify(body)}`; if (!keys.has(fingerprint)) keys.set(fingerprint,crypto.randomUUID()); return keys.get(fingerprint); }
function clear(node){ node.replaceChildren(); }
function line(node,text,tag='p'){ const el=document.createElement(tag);el.textContent=text;node.append(el);return el; }
function assert(value,message){ if(!value) throw new Error(message);return value; }
function record(path,payload){ const li=document.createElement('li');li.textContent=`${path} · ${payload.capability||'request'} · receipt ${payload.receipt?.receipt_id||payload.receipt?.id||'none'} · trace ${payload.trace_id||'not supplied'}`;$('events').prepend(li); }
async function api(path,{method='GET',body,participant=false}={}){
 const headers={Accept:'application/json'};if(body!==undefined)headers['Content-Type']='application/json';
 if(method!=='GET')headers['Idempotency-Key']=keyFor(path,body);
 if(participant){assert(state.participant,'Enter an access code first.');headers.Authorization=`Bearer ${state.participant}`;}
 let response;
 try { response=await fetch(path,{method,headers,credentials:participant?'omit':'same-origin',body:body===undefined?undefined:JSON.stringify(body)}); }
 catch {throw new Error(method==='GET'?'Connection unavailable. Retry when the server is reachable.':'Outcome unknown. Retry this same action without changing inputs; its request key is retained.');}
 let payload;try{payload=await response.json();}catch{throw new Error(`Server returned an unreadable response (${response.status}). No success is assumed.`);}
 if(!response.ok || payload.ok===false){const e=new Error(`${payload.error?.code||response.status}: ${payload.error?.message||'Request could not complete.'}`);e.code=payload.error?.code;e.status=response.status;throw e;}
 record(path,payload);return payload;
}
async function run(label,work){if(busy)return;busy=true;$('error').hidden=true;$('status').textContent=label;const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await work();$('status').textContent=`${label.replace(/…$/,'')} — completed.`;}catch(e){$('error').textContent=e.message;$('error').hidden=false;$('status').textContent='Action needs attention. No completion is assumed.';}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
function formAction(id,label,handler){$(id).addEventListener('submit',e=>{e.preventDefault();run(label,()=>handler(new FormData(e.currentTarget)));});}
function click(id,label,handler){$(id).addEventListener('click',()=>run(label,handler));}
function items(result){return Array.isArray(result)?result:result?.items||result?.projects||result?.templates||[];}
function assessmentPath(){return `/v2/assessments/${encodeURIComponent(assert(state.assessment?.assessment_id,'Create or load an assessment first.'))}`;}
function surveyPath(){return `${assessmentPath()}/surveys/${encodeURIComponent(assert(state.survey?.assessment_survey_id,'Attach a survey first.'))}`;}
function showAssessment(){const a=state.assessment;clear($('assessment'));if(!a)return;line($('assessment'),a.name||'Saved assessment','strong');line($('assessment'),`ID: ${a.assessment_id}`);line($('assessment'),`Stage: ${a.stage}; revision: ${a.revision??"not supplied"}`);$('reopen-form').elements.id.value=a.assessment_id;const url=new URL(location.href);url.searchParams.set('assessment',a.assessment_id);history.replaceState(null,'',url);}
async function loadProjects(){const p=await api('/v2/projects');clear($('projects'));let option=new Option('Choose a project','');$('projects').add(option);for(const item of items(p.result))$('projects').add(new Option(item.name||item.project_id||item.id,item.project_id||item.id));}
async function loadTemplates(){const p=await api('/v2/templates');state.templates=items(p.result);clear($('templates'));$('templates').add(new Option('Choose a template',''));state.templates.forEach((t,i)=>$('templates').add(new Option(`${t.label||t.template_id} · ${t.version}`,String(i))));}
async function loadAssessment(id){const p=await api(`/v2/assessments/${encodeURIComponent(id)}`);state.assessment={...p.result,assessment_id:p.result.assessment_id||p.result.id};state.survey=null;state.batch=null;state.intent=null;$('code-display').hidden=true;$('export-preview').hidden=true;$('survey').textContent='Attach a survey or resume using its server-provided selection.';showAssessment();if(p.result.assessment_survey_id){state.survey={assessment_survey_id:p.result.assessment_survey_id};$('survey').textContent=`Saved survey: ${state.survey.assessment_survey_id}`;}}
async function loadIdentity(){try{const p=await api('/v2/me');$('identity').textContent=`Session: ${p.result.display_name||p.result.principal_id}`;$('dev-login').hidden=true;await loadProjects();await loadTemplates();const id=new URL(location.href).searchParams.get('assessment');if(id)await loadAssessment(id);}catch(e){$('identity').textContent='No authenticated facilitator session.';$('dev-login').hidden=false;if(e.status!==401)throw e;}}
click('dev-login','Starting local synthetic session…',async()=>{await api('/v2/dev/session',{method:'POST',body:{}});await loadIdentity();});
formAction('project-form','Creating project…',async fd=>{const p=await api('/v2/projects',{method:'POST',body:{name:fd.get('name').trim()}});await loadProjects();$('projects').value=p.result.project_id||p.result.id;});
formAction('assessment-form','Creating assessment…',async fd=>{const pid=assert($('projects').value,'Choose a project first.');const p=await api(`/v2/projects/${encodeURIComponent(pid)}/assessments`,{method:'POST',body:{name:fd.get('name').trim(),language:{new:{label:fd.get('language').trim()}}}});state.assessment={...p.result,assessment_id:p.result.assessment_id||p.result.id};state.survey=null;showAssessment();});
formAction('reopen-form','Loading saved assessment…',fd=>loadAssessment(fd.get('id').trim()));
click('select-survey','Attaching survey…',async()=>{const index=assert($('templates').value!=='' ? $('templates').value:null,'Choose a survey template.');const t=state.templates[Number(index)];const p=await api(`${assessmentPath()}/surveys`,{method:'POST',body:{template_id:t.template_id,template_version:t.version,expected_revision:state.assessment.revision}});state.survey={...p.result,assessment_survey_id:p.result.assessment_survey_id||p.result.id};if(p.result.revision)state.assessment.revision=p.result.revision;$('survey').textContent=`${t.label||t.template_id} · version ${t.version} · ${p.result.assessment_survey_id}`;});
click('open-collection','Opening collection…',async()=>{const p=await api(`${assessmentPath()}/stage`,{method:'POST',body:{stage:'collect',expected_revision:state.assessment.revision}});state.assessment={...state.assessment,...p.result};showAssessment();});
click('issue-code','Preparing code disclosure…',async()=>{const p=await api(`${surveyPath()}/codes`,{method:'POST',body:{count:1}});state.batch=p.result;const preview=await api(`${surveyPath()}/codes/export`,{method:'POST',body:{batch_id:state.batch.batch_id,mode:'dry_run'}});state.intent=assert(preview.result.confirm_token,'Server supplied no confirmation token.');$('export-preview').hidden=false;$('code-display').hidden=true;});
click('confirm-export','Revealing authorized access code…',async()=>{assert(state.intent,'Prepare the disclosure preview first.');const p=await api(`${surveyPath()}/codes/export`,{method:'POST',body:{batch_id:state.batch.batch_id,mode:'execute',confirm_token:state.intent}});const values=(p.result.codes||[]).map(c=>typeof c==='string'?c:c.code).filter(Boolean);assert(values.length,'Server returned no code values.');$('code-display').textContent=values.join('\n');$('code-display').hidden=false;$('export-preview').hidden=true;state.intent=null;});
$('cancel-export').onclick=()=>{$('export-preview').hidden=true;state.intent=null;};
function resetParticipant(){state.participant=null;state.form=null;state.answers=[];state.submitted=false;$('response-form').hidden=true;$('review').hidden=true;$('receipt').hidden=true;$('recover-receipt').hidden=true;$('clear-participant').hidden=true;$('form-context').textContent='';clear($('questions'));$('redeem-form').reset();}
function drawForm(){const f=state.form;clear($('questions'));$('form-context').textContent=`Template ${f.template_id} · version ${f.template_version} · form revision ${f.form_revision}`;for(const item of f.items||[]){const field=document.createElement('fieldset');field.dataset.item=item.item_id;line(field,item.label||item.item_id,'legend');const options=item.options||[];const kind=item.kind||item.type;if(options.length){const multi=/multi|checkbox/.test(kind||'');for(const o of options){const label=document.createElement('label');const input=document.createElement('input');input.type=multi?'checkbox':'radio';input.name=item.item_id;input.value=o.option_id??o.value??o.id;input.required=!!item.required&&!multi;label.append(input,document.createTextNode(o.label||String(input.value)));field.append(label);}if(multi&&item.required)field.dataset.requiredMulti='true';}else{const input=document.createElement('input');input.name=item.item_id;input.type=/number|scale/.test(kind||'')?'number':'text';input.required=!!item.required;input.setAttribute('aria-label',item.label||item.item_id);field.append(input);}$('questions').append(field);}$('response-form').hidden=false;$('review').hidden=true;$('receipt').hidden=true;$('clear-participant').hidden=false;}
formAction('redeem-form','Opening participant form…',async fd=>{const code=fd.get('code').trim();resetParticipant();const p=await api('/v2/participate/code',{method:'POST',body:{code}});state.participant=assert(p.result.participant_token,'Server did not return participant session.');const f=await api('/v2/participate/form',{participant:true});state.form={...f.result,template_id:f.result.template_id||f.result.template?.id};drawForm();$('recover-receipt').hidden=false;});
formAction('response-form','Preparing answer review…',async()=>{assert(!state.submitted,'This participant already submitted.');const answers=[];for(const item of state.form.items||[]){const elements=[...$('questions').querySelectorAll('input')].filter(i=>i.name===item.item_id);const multi=elements[0]?.type==='checkbox';let value;if(multi){value=elements.filter(e=>e.checked).map(e=>e.value);if(item.required&&!value.length){elements[0].focus();throw new Error(`Select an answer for ${item.label||item.item_id}.`);}}else if(elements[0]?.type==='radio')value=elements.find(e=>e.checked)?.value??null;else{const input=elements[0];value=input?.value===''?null:input?.type==='number'?Number(input.value):input?.value;}answers.push({item_id:item.item_id,value});}state.answers=answers;clear($('review-answers'));for(const answer of answers){const item=state.form.items.find(i=>i.item_id===answer.item_id);const vals=Array.isArray(answer.value)?answer.value:[answer.value];const names=vals.map(v=>(item.options||[]).find(o=>(o.option_id??o.value??o.id)===v)?.label??v??'Not answered');line($('review-answers'),`${item.label||item.item_id}: ${names.join(', ')}`);}$('review').hidden=false;$('response-form').hidden=true;$('submit-response').focus();});
$('edit-response').onclick=()=>{$('review').hidden=true;$('response-form').hidden=false;};
function showReceipt(p){clear($('receipt'));line($('receipt'),'Response saved','strong');line($('receipt'),`Response: ${p.result.response_id}`);line($('receipt'),`Submitted: ${p.result.submitted_at||p.receipt?.at||"Recorded by server"}`);line($('receipt'),`Receipt: ${p.receipt?.receipt_id||p.receipt?.id||p.result.receipt_id||'See server response'}`);$('receipt').hidden=false;$('review').hidden=true;$('response-form').hidden=true;state.submitted=true;}
click('submit-response','Saving response…',async()=>{assert(state.form,'Open a survey first.');const p=await api('/v2/participate/responses',{method:'POST',participant:true,body:{form_revision:state.form.form_revision,template_version:state.form.template_version,answers:state.answers}});showReceipt(p);});
click('recover-receipt','Recovering saved receipt…',async()=>showReceipt(await api('/v2/participate/receipt',{participant:true})));
$('clear-participant').onclick=resetParticipant;
click('load-results','Loading persisted result…',async()=>{const p=await api(`${assessmentPath()}/results`);clear($('result-view'));const r=p.result;line($('result-view'),r.state==='policy_held'?'Scoring policy held':r.suppressed?'Result suppressed':'Persisted result','strong');if(r.synthetic_submission_count!==undefined||r.synthetic&&r.submission_count!==undefined)line($('result-view'),`Synthetic submissions saved: ${r.synthetic_submission_count??r.submission_count}`);if(r.state==='policy_held'||r.suppressed)line($('result-view'),'No private scores are disclosed. This verifies persistence, not scoring completion.');else line($('result-view'),JSON.stringify(r));});
run('Checking session…',loadIdentity);
